"use client";
import { useState } from "react";

type Report = { id: string; post_id: string | null; reply_id: string | null; reporter_id: string; reason: string; details: string | null; status: string; created_at: string };
export function CommunityReportsQueue({ reports }: { reports: Report[] }) {
  const [items, setItems] = useState(reports);
  const update = async (reportId: string, status: string) => { const response = await fetch("/api/community", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "moderate_report", reportId, status }) }); if (response.ok) setItems((current) => current.filter((item) => item.id !== reportId)); };
  return <main className="mx-auto min-h-screen w-full max-w-4xl p-6"><p className="text-xs font-black uppercase tracking-[0.16em] text-[var(--br-action)]">Community safety</p><h1 className="mt-2 text-3xl font-extrabold">Report queue</h1><p className="mt-2 text-sm text-[var(--br-text-muted)]">Review learner reports before they become a pattern.</p><section className="mt-6 grid gap-3">{items.length ? items.map((report) => <article key={report.id} className="rounded-2xl border border-[var(--br-border)] bg-surface p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-extrabold">{report.reason}</p><p className="mt-1 text-xs text-[var(--br-text-muted)]">{report.post_id ? "Post" : "Reply"} · {new Date(report.created_at).toLocaleString()}</p>{report.details ? <p className="mt-3 text-sm">{report.details}</p> : null}</div><span className="rounded-full bg-[var(--br-surface-muted)] px-2 py-1 text-[10px] font-extrabold">{report.status}</span></div><div className="mt-4 flex gap-2"><button type="button" onClick={() => void update(report.id, "IN_REVIEW")} className="rounded-lg border border-[var(--br-border)] px-3 py-2 text-xs font-bold">Mark in review</button><button type="button" onClick={() => void update(report.id, "RESOLVED")} className="rounded-lg bg-[var(--br-action)] px-3 py-2 text-xs font-bold text-on-dark">Resolve</button><button type="button" onClick={() => void update(report.id, "DISMISSED")} className="rounded-lg border border-[var(--br-border)] px-3 py-2 text-xs font-bold">Dismiss</button></div></article>) : <div className="rounded-2xl border border-dashed border-[var(--br-border)] p-10 text-center text-sm text-[var(--br-text-muted)]">No open community reports.</div>}</section></main>;
}
