import Link from "next/link";
import { ArrowRight, Check, LockKeyhole, Sparkles, Trophy } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { getLearnerAchievements, type AchievementMilestone } from "@/lib/achievements";
import { LearnerAppShell } from "@/components/LearnerAppShell";

const toneStyles = {
  purple: "from-[var(--br-chart-primary)] to-[var(--br-brand)]",
  orange: "from-[var(--br-achievement)] to-[#FF6B00]",
  green: "from-[var(--br-success)] to-[#00957A]",
  red: "from-[var(--br-danger)] to-[#C0002A]",
};

function MilestoneCard({ item }: { item: AchievementMilestone }) {
  const percentage = Math.min(100, Math.round((item.progress / item.target) * 100));
  return <article className={`relative overflow-hidden rounded-[20px] border bg-white p-4 shadow-[0_10px_26px_rgba(20,23,43,.05)] ${item.unlocked ? "border-[#DDEDE6]" : "border-[var(--br-surface-strong)]"}`}><div className="flex items-start gap-3"><div className={`grid size-12 shrink-0 place-items-center rounded-2xl bg-gradient-to-br ${toneStyles[item.tone]} text-2xl ${item.unlocked ? "" : "grayscale opacity-45"}`}>{item.unlocked ? item.icon : <LockKeyhole className="size-5 text-white" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="break-words font-extrabold text-[var(--br-dark-card)]">{item.title}</h3>{item.unlocked ? <span className="rounded-full bg-[color-mix(in_srgb,var(--br-success)_12%,var(--br-surface))] px-2 py-0.5 text-[10px] font-black text-[#168E69]">Unlocked</span> : null}</div><p className="mt-1 text-xs leading-5 text-[var(--br-text-muted)]">{item.description}</p></div></div><div className="mt-4 flex items-center gap-2"><div className="h-2 min-w-0 flex-1 overflow-hidden rounded-full bg-[#EEF0F7]"><div className={`h-full rounded-full bg-gradient-to-r ${toneStyles[item.tone]}`} style={{ width: `${percentage}%` }} /></div><span className="shrink-0 text-[11px] font-black text-[var(--br-text-muted)]">{Math.min(item.progress, item.target)}/{item.target} {item.unit}</span></div></article>;
}

function MilestoneSection({ title, description, items }: { title: string; description: string; items: AchievementMilestone[] }) {
  return <section className="rounded-[20px] border border-[var(--br-surface-strong)] bg-white p-4 shadow-[0_10px_28px_rgba(0,0,0,.05)] sm:p-5"><div className="mb-4"><h2 className="text-lg font-extrabold text-[var(--br-dark-card)]">{title}</h2><p className="mt-1 text-sm text-[var(--br-text-muted)]">{description}</p></div><div className="grid gap-3 md:grid-cols-2">{items.map((item) => <MilestoneCard key={item.id} item={item} />)}</div></section>;
}

export default async function AchievementsPage() {
  const { user } = await requireUser();
  const achievements = await getLearnerAchievements(createAdminClient(), user.id);
  const unlocked = [...achievements.quizBadges, ...achievements.streakMilestones, ...achievements.practiceMilestones, ...achievements.evidenceMilestones].filter((item) => item.unlocked).length;
  const total = achievements.quizBadges.length + achievements.streakMilestones.length + achievements.practiceMilestones.length + achievements.evidenceMilestones.length;
  return <LearnerAppShell active="achievements"><section className="rounded-[22px] bg-gradient-to-br from-[var(--br-brand-strong)] via-[var(--br-dark-card)] to-[var(--br-dark-card)] p-5 text-white shadow-[0_16px_48px_rgba(20,23,80,.2)] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-white/60"><Sparkles size={16}/>Your achievement path</p><h1 className="mt-2 text-2xl font-extrabold sm:text-[28px]">Keep becoming the learner you want to be.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-white/70">Every badge is connected to a real learning action: practice, consistency, quiz performance, or course evidence.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-5 py-3 text-right backdrop-blur"><p className="text-2xl font-black">{unlocked}/{total}</p><p className="text-xs font-bold text-white/65">milestones unlocked</p></div></div></section><div className="grid gap-5 xl:grid-cols-2"><MilestoneSection title="Quiz badges" description={`Your current quiz badge is ${achievements.quizBadge.name}. Earn points through completed quiz attempts.`} items={achievements.quizBadges}/><MilestoneSection title="Streak journey" description={`You are on a ${achievements.streak}-day active streak. Keep one small learning action going each day.`} items={achievements.streakMilestones}/><MilestoneSection title="Practice habit" description="Lesson and quiz attempts build the habit that makes progress durable." items={achievements.practiceMilestones}/><MilestoneSection title="Course evidence" description="These milestones use your best scored evidence from mapped course learning." items={achievements.evidenceMilestones}/></div><section className="rounded-[20px] border border-[#E8E2FF] bg-[#F7F4FF] p-4 sm:p-5"><div className="flex items-start gap-3"><Trophy className="mt-0.5 text-[var(--br-chart-primary)]" size={20}/><div><h2 className="font-extrabold text-[var(--br-dark-card)]">Your next move</h2><p className="mt-1 text-sm leading-6 text-[var(--br-text-muted)]">Take a quiz, continue an enrolled course, or plan a small task. BrenUp updates this page from your real activity.</p><div className="mt-3 flex flex-wrap gap-2"><Link href="/quizzes" className="inline-flex items-center gap-2 rounded-xl bg-[var(--br-chart-primary)] px-3.5 py-2.5 text-xs font-extrabold text-white">Play a quiz <ArrowRight size={14}/></Link><Link href="/tasks/planner" className="inline-flex items-center gap-2 rounded-xl border border-[#DCD2FF] bg-white px-3.5 py-2.5 text-xs font-extrabold text-[var(--br-chart-primary)]">Plan practice <ArrowRight size={14}/></Link></div></div></div></section></LearnerAppShell>;
}
