import Link from "next/link";
import { ArrowLeft, Search, UsersRound } from "lucide-react";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireSchoolWorkspace } from "@/lib/schoolAccess";

export default async function SchoolLearnersPage({ searchParams }: { searchParams: Promise<{ q?: string; org?: string }> }) {
  const session = await requireSchoolWorkspace(); const { q = "", org } = await searchParams; const admin = createAdminClient();
  let orgQuery = admin.from("organizations").select("id,name,brand_name").order("name"); if (session.organizationIds) orgQuery = orgQuery.in("id", session.organizationIds);
  const { data: organizations } = await orgQuery; const organization = (organizations ?? []).find((item) => item.id === org) ?? organizations?.[0] ?? null;
  if (!organization) return <main><h1 className="text-2xl font-semibold">Learners</h1><p className="mt-2 text-sm text-[var(--br-text-muted)]">No school is linked to this account.</p></main>;
  const { data: classes } = await admin.from("classes").select("id,name").eq("organization_id", organization.id).order("name"); const classIds = (classes ?? []).map((row) => row.id);
  const { data: members } = classIds.length ? await admin.from("class_members").select("class_id,user_id").in("class_id", classIds).eq("role", "STUDENT") : { data: [] };
  const learnerIds = [...new Set((members ?? []).map((row) => row.user_id))]; const { data: profiles } = learnerIds.length ? await admin.from("profiles").select("id,full_name,first_name,last_name,cefr_level,avatar_url,created_at").in("id", learnerIds).order("full_name") : { data: [] };
  const query = q.trim().toLowerCase(); const classNames = new Map((classes ?? []).map((row) => [row.id, row.name])); const classesByLearner = new Map<string, string[]>(); for (const member of members ?? []) classesByLearner.set(member.user_id, [...(classesByLearner.get(member.user_id) ?? []), classNames.get(member.class_id) ?? "Class"]);
  const filtered = (profiles ?? []).filter((profile) => !query || `${profile.full_name ?? ""} ${profile.first_name ?? ""} ${profile.last_name ?? ""}`.toLowerCase().includes(query));
  return <main className="min-w-0"><Link href={`/admin/school?org=${organization.id}`} className="inline-flex items-center gap-1.5 text-sm font-semibold text-[var(--br-text-muted)] hover:text-violetglow"><ArrowLeft size={15} /> School workspace</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-violetglow">{organization.brand_name || organization.name}</p><h1 className="mt-1 text-2xl font-semibold sm:text-3xl">Learners</h1><p className="mt-2 text-sm text-[var(--br-text-muted)]">Only learners attached to classes in this school appear here.</p></div><p className="rounded-lg bg-violetglow/10 px-3 py-2 text-sm font-bold text-violetglow">{filtered.length} learners</p></div><form className="mt-5 flex max-w-md items-center gap-2 rounded-lg border border-[var(--br-border)] bg-surface px-3 py-2 shadow-sm"><Search size={16} className="text-[var(--br-text-muted)]" /><input name="q" defaultValue={q} placeholder="Search learners" className="w-full bg-transparent text-sm outline-none" /><input name="org" type="hidden" value={organization.id} /></form><section className="mt-5 overflow-hidden rounded-xl border border-[var(--br-border)] bg-surface shadow-sm"><div className="hidden grid-cols-[minmax(0,1.4fr)_minmax(0,1.2fr)_120px_120px] gap-4 border-b border-[var(--br-border)] bg-surface-muted px-5 py-3 text-[11px] font-bold uppercase tracking-wide text-[var(--br-text-muted)] md:grid"><span>Learner</span><span>Classes</span><span>Level</span><span>Joined</span></div><div className="divide-y divide-black/10">{filtered.map((learner) => { const name = learner.full_name?.trim() || [learner.first_name, learner.last_name].filter(Boolean).join(" ") || "Learner"; return <article key={learner.id} className="grid gap-3 px-5 py-4 md:grid-cols-[minmax(0,1.4fr)_minmax(0,1.2fr)_120px_120px] md:items-center"><div className="flex min-w-0 items-center gap-3"><div className="grid size-9 shrink-0 place-items-center overflow-hidden rounded-full bg-violetglow/10 text-xs font-bold text-violetglow">{learner.avatar_url ? <img src={learner.avatar_url} alt="" className="size-full object-cover" /> : name.slice(0, 2).toUpperCase()}</div><p className="truncate font-semibold">{name}</p></div><p className="text-sm text-[var(--br-text-muted)]">{(classesByLearner.get(learner.id) ?? []).join(", ") || "No active class"}</p><span className="w-fit rounded-full bg-moss/10 px-2.5 py-1 text-xs font-bold text-moss">{learner.cefr_level || "—"}</span><p className="text-sm text-[var(--br-text-muted)]">{new Date(learner.created_at).toLocaleDateString()}</p></article>; })}{!filtered.length ? <div className="grid min-h-52 place-items-center p-6 text-center"><div><UsersRound className="mx-auto text-[var(--br-text-muted)]" size={28} /><p className="mt-3 text-sm text-[var(--br-text-muted)]">No school learners found.</p></div></div> : null}</div></section></main>;
}
