import Link from "next/link";
import { CalendarDays, Radio, UsersRound } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { LearnerAppShell } from "@/components/LearnerAppShell";
import { LearnerPageHero } from "@/components/LearnerPageHero";

export default async function LearnerLiveClassesPage() {
  const { user } = await requireUser(); const admin = createAdminClient();
  const { data: memberships } = await admin.from("class_members").select("class_id").eq("user_id", user.id).eq("role", "STUDENT");
  const classIds = (memberships ?? []).map((item) => item.class_id);
  const { data: sessions } = classIds.length ? await admin.from("live_sessions").select("id,class_id,title,status,scheduled_at,duration_minutes,classes(name)").in("class_id", classIds).in("status", ["SCHEDULED", "LIVE", "COMPLETED"]).order("scheduled_at", { ascending: true, nullsFirst: false }) : { data: [] };
  const list = sessions ?? []; const live = list.filter((item) => item.status === "LIVE"); const ordered = [...live, ...list.filter((item) => item.status === "SCHEDULED"), ...list.filter((item) => item.status === "COMPLETED")];
  return <LearnerAppShell active="live-classes"><LearnerPageHero eyebrow="Live classroom" eyebrowIcon={Radio} title="Learn together, live." description="Join your teacher’s synchronized lesson, respond to activities, and stay connected with the class." aside={<div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-right"><p className="text-2xl font-extrabold">{live.length}</p><p className="text-xs font-semibold text-white/65">live now</p></div>} /><section className="rounded-[20px] border border-[var(--br-border)] bg-[var(--br-surface)] p-4 shadow-[var(--br-shadow)] sm:p-5"><h2 className="text-lg font-extrabold">Your live classes</h2><div className="mt-4 grid gap-3">{ordered.map((session) => { const klass = Array.isArray(session.classes) ? session.classes[0] : session.classes; return <Link key={session.id} href={`/live/${session.id}`} className="flex items-center gap-3 rounded-xl border border-[var(--br-border)] p-3 transition hover:border-[var(--br-brand)]/25 hover:bg-[var(--br-surface-muted)]"><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${session.status === "LIVE" ? "bg-[color-mix(in_srgb,var(--br-success)_12%,var(--br-surface))] text-[var(--br-chart-secondary)]" : "bg-[var(--br-surface-muted)] text-[var(--br-brand)]"}`}>{session.status === "LIVE" ? <Radio size={19} /> : <CalendarDays size={19} />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-extrabold">{session.title}</h3><span className="rounded-full bg-[var(--br-surface-muted)] px-2 py-0.5 text-[10px] font-bold text-[var(--br-text-muted)]">{session.status}</span></div><p className="mt-1 text-xs text-[var(--br-text-muted)]">{klass?.name || "Class"} · {session.scheduled_at ? new Date(session.scheduled_at).toLocaleString() : "Time to be confirmed"} · {session.duration_minutes} min</p></div><span className="text-sm font-bold text-[var(--br-brand)]">{session.status === "LIVE" ? "Join" : session.status === "COMPLETED" ? "Review" : "Details"}</span></Link>; })}{!list.length ? <div className="grid min-h-52 place-items-center text-center"><div><UsersRound className="mx-auto text-[var(--br-text-muted)]" size={30} /><h3 className="mt-3 font-extrabold">No live classes yet.</h3><p className="mt-1 text-sm text-[var(--br-text-muted)]">When your teacher schedules one for your class, it will appear here.</p></div></div> : null}</div></section></LearnerAppShell>;
}
