import Link from "next/link";
import { CalendarDays, Radio, UsersRound } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { LearnerAppShell } from "@/components/LearnerAppShell";

export default async function LearnerLiveClassesPage() {
  const { user } = await requireUser(); const admin = createAdminClient();
  const { data: memberships } = await admin.from("class_members").select("class_id").eq("user_id", user.id).eq("role", "STUDENT");
  const classIds = (memberships ?? []).map((item) => item.class_id);
  const { data: sessions } = classIds.length ? await admin.from("live_sessions").select("id,class_id,title,status,scheduled_at,duration_minutes,classes(name)").in("class_id", classIds).in("status", ["SCHEDULED", "LIVE", "COMPLETED"]).order("scheduled_at", { ascending: true, nullsFirst: false }) : { data: [] };
  const list = sessions ?? []; const live = list.filter((item) => item.status === "LIVE"); const ordered = [...live, ...list.filter((item) => item.status === "SCHEDULED"), ...list.filter((item) => item.status === "COMPLETED")];
  return <LearnerAppShell active="live-classes"><section className="rounded-[24px] bg-gradient-to-br from-[#1A1060] via-[#0C1945] to-[#0E1F5A] p-5 text-white shadow-[0_16px_48px_rgba(20,23,80,.2)] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-white/60"><Radio size={15} /> Live classroom</div><h1 className="mt-2 text-2xl font-extrabold sm:text-[28px]">Learn together, live.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-white/70">Join your teacher’s synchronized lesson, respond to activities, and stay connected with the class.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-right"><p className="text-2xl font-extrabold">{live.length}</p><p className="text-xs font-semibold text-white/65">live now</p></div></div></section><section className="rounded-[20px] border border-[#ECECF5] bg-white p-4 shadow-[0_10px_28px_rgba(0,0,0,.05)] sm:p-5"><h2 className="text-lg font-extrabold">Your live classes</h2><div className="mt-4 grid gap-3">{ordered.map((session) => { const klass = Array.isArray(session.classes) ? session.classes[0] : session.classes; return <Link key={session.id} href={`/live/${session.id}`} className="flex items-center gap-3 rounded-xl border border-[#ECECF5] p-3 transition hover:border-[#6C3BFF]/25 hover:bg-[#FAF9FF]"><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${session.status === "LIVE" ? "bg-[#E7FBF4] text-[#00A978]" : "bg-[#EEEAFB] text-[#6C3BFF]"}`}>{session.status === "LIVE" ? <Radio size={19} /> : <CalendarDays size={19} />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-extrabold">{session.title}</h3><span className="rounded-full bg-[#F1F2F7] px-2 py-0.5 text-[10px] font-bold text-[#6E738D]">{session.status}</span></div><p className="mt-1 text-xs text-[#6E738D]">{klass?.name || "Class"} · {session.scheduled_at ? new Date(session.scheduled_at).toLocaleString() : "Time to be confirmed"} · {session.duration_minutes} min</p></div><span className="text-sm font-bold text-[#6C3BFF]">{session.status === "LIVE" ? "Join" : session.status === "COMPLETED" ? "Review" : "Details"}</span></Link>; })}{!list.length ? <div className="grid min-h-52 place-items-center text-center"><div><UsersRound className="mx-auto text-[#A6AAC0]" size={30} /><h3 className="mt-3 font-extrabold">No live classes yet.</h3><p className="mt-1 text-sm text-[#6E738D]">When your teacher schedules one for your class, it will appear here.</p></div></div> : null}</div></section></LearnerAppShell>;
}
