"use client";

import { Clock3, Eye, Lock, LockOpen, RotateCcw, X } from "lucide-react";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

export function LiveTeacherToolbar({ sessionId, activities, navigationLocked }: { sessionId: string; activities: Array<{ id: string; activity_type: string }>; navigationLocked: boolean }) {
  const [locked, setLocked] = useState(navigationLocked); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  async function control(payload: Record<string, unknown>) { setBusy(true); setNotice(null); try { const r = await fetch(`/api/live/${sessionId}/controls`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.error || "Could not update the class."); void createClient().channel(`brenup-live:${sessionId}`).send({ type: "broadcast", event: "control", payload }); setNotice("Updated"); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not update the class."); } finally { setBusy(false); } }
  return <div className="mt-2 rounded-xl border border-[var(--br-chart-primary)]/15 bg-[var(--br-surface-muted)] p-2"><div className="flex flex-wrap items-center gap-1.5"><button type="button" disabled={busy} onClick={() => { const next = !locked; setLocked(next); void control({ action: "lock", locked: next }); }} className="inline-flex items-center gap-1 rounded-md bg-surface px-2 py-1.5 text-[11px] font-extrabold text-[var(--br-chart-primary)] shadow-sm">{locked ? <Lock size={12} /> : <LockOpen size={12} />}{locked ? "Navigation locked" : "Navigation open"}</button><button type="button" disabled={busy} onClick={() => void control({ action: "timer", seconds: 300 })} className="inline-flex items-center gap-1 rounded-md bg-surface px-2 py-1.5 text-[11px] font-extrabold text-[var(--br-chart-primary)] shadow-sm"><Clock3 size={12} />5 min</button><button type="button" disabled={busy} onClick={() => void control({ action: "timer", seconds: 0 })} className="inline-flex items-center gap-1 rounded-md bg-surface px-2 py-1.5 text-[11px] font-extrabold text-[var(--br-chart-primary)] shadow-sm"><X size={12} />Clear timer</button>{notice ? <span className="text-[11px] font-bold text-[var(--br-chart-secondary)]">{notice}</span> : null}</div>{activities.length ? <div className="mt-2 flex flex-wrap gap-1.5">{activities.map((activity, index) => <span key={activity.id} className="inline-flex items-center gap-1 rounded-md border border-[var(--br-chart-primary)]/15 bg-surface px-1.5 py-1 text-[10px] font-bold text-[var(--br-text-muted)]">Activity {index + 1}<button type="button" disabled={busy} onClick={() => void control({ action: "activity", activityId: activity.id, state: "OPEN", seconds: 300 })} className="text-[var(--br-chart-secondary)]">Open 5m</button><button type="button" disabled={busy} onClick={() => void control({ action: "activity", activityId: activity.id, state: "OPEN" })} className="text-[var(--br-chart-primary)]">Open</button><button type="button" disabled={busy} onClick={() => void control({ action: "activity", activityId: activity.id, state: "CLOSED" })} className="text-[var(--br-danger)]">Close</button><button type="button" disabled={busy} title="Give two more minutes" onClick={() => void control({ action: "activity", activityId: activity.id, state: "EXTEND", seconds: 120 })}><Clock3 size={11} /></button><button type="button" disabled={busy} title="Reveal answers" onClick={() => void control({ action: "activity", activityId: activity.id, state: "REVEALED" })}><Eye size={11} /></button><button type="button" disabled={busy} title="Reset activity" onClick={() => void control({ action: "activity", activityId: activity.id, state: "RESET" })}><RotateCcw size={11} /></button></span>)}</div> : null}</div>;
}
