"use client";

import { useMemo, useState, useTransition } from "react";
import { Check, Image as ImageIcon, Save, Search, X } from "lucide-react";
import { updatePracticeModuleMetadata } from "@/app/admin/activities/actions";

const categories = [["GRAMMAR", "Grammar"], ["VOCABULARY", "Vocabulary"], ["READING", "Reading"], ["WRITING", "Writing"], ["LISTENING", "Listening"], ["SPEAKING", "Speaking"]];
type MediaImage = { id: string; title: string | null; url: string; altText: string | null };

export function PracticeModuleSettings({ initial, mediaImages }: { initial: { id: string; title: string; description: string; category: string; level: string; accessType: string; status: "DRAFT" | "PUBLISHED"; featureImagePath: string }; mediaImages: MediaImage[] }) {
  const [title, setTitle] = useState(initial.title);
  const [description, setDescription] = useState(initial.description);
  const [category, setCategory] = useState(initial.category);
  const [level, setLevel] = useState(initial.level);
  const [accessType, setAccessType] = useState(initial.accessType === "ENROLLED" ? "FREE" : initial.accessType);
  const [status, setStatus] = useState(initial.status);
  const [featureImagePath, setFeatureImagePath] = useState(initial.featureImagePath);
  const [pickerOpen, setPickerOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  const selectedImage = mediaImages.find((image) => image.url === featureImagePath || image.id === featureImagePath);
  const visibleImages = useMemo(() => mediaImages.filter((image) => `${image.title ?? ""} ${image.altText ?? ""}`.toLowerCase().includes(search.trim().toLowerCase())), [mediaImages, search]);
  const save = (nextStatus: "DRAFT" | "PUBLISHED") => startTransition(async () => {
    try { await updatePracticeModuleMetadata(initial.id, { title, description, category, level, accessType, status: nextStatus, featureImagePath }); setStatus(nextStatus); setMessage(nextStatus === "PUBLISHED" ? "Module published." : "Draft saved."); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Could not save module details."); }
  });
  return <section className="mb-4 rounded-2xl border border-[var(--br-border)] bg-surface p-4 shadow-sm sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[var(--br-brand)]">Practice Module</p><h1 className="mt-1 text-xl font-extrabold">Module details</h1></div><span className="rounded-full bg-[var(--br-surface-muted)] px-3 py-1 text-xs font-extrabold">{status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">Title<input value={title} onChange={(event) => setTitle(event.target.value)} className="mt-1 w-full rounded-xl border border-[var(--br-border)] px-3 py-2.5 font-normal" /></label><label className="text-sm font-bold sm:col-span-2">Description<textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={2} className="mt-1 w-full rounded-xl border border-[var(--br-border)] px-3 py-2.5 font-normal" /></label><label className="text-sm font-bold">Category<select value={category} onChange={(event) => setCategory(event.target.value)} className="mt-1 w-full rounded-xl border border-[var(--br-border)] px-3 py-2.5 font-normal">{categories.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-bold">CEFR level<select value={level} onChange={(event) => setLevel(event.target.value)} className="mt-1 w-full rounded-xl border border-[var(--br-border)] px-3 py-2.5 font-normal">{["A1", "A2", "B1", "B2", "C1"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-bold sm:col-span-2">Access<select value={accessType} onChange={(event) => setAccessType(event.target.value)} className="mt-1 w-full rounded-xl border border-[var(--br-border)] px-3 py-2.5 font-normal"><option value="FREE">Free · account required</option><option value="PREMIUM">Premium · Practice Library access required</option></select></label>
      <div className="sm:col-span-2"><p className="text-sm font-bold">Feature image <span className="font-normal text-[var(--br-text-muted)]">(required to publish)</span></p><button type="button" onClick={() => setPickerOpen(true)} className="mt-1 flex w-full items-center gap-3 rounded-xl border border-[var(--br-border)] bg-[var(--br-surface-muted)] p-2 text-left hover:bg-surface">{selectedImage ? <img src={selectedImage.url} alt={selectedImage.altText || ""} className="h-16 w-24 rounded-lg object-cover" /> : <span className="grid h-16 w-24 place-items-center rounded-lg border border-dashed border-[var(--br-border)] text-[var(--br-text-muted)]"><ImageIcon size={20} /></span>}<span><span className="block text-sm font-bold">{selectedImage?.title || (featureImagePath ? "Selected image" : "Choose from Media Library")}</span><span className="mt-1 block text-xs text-[var(--br-text-muted)]">Select a saved image for the learner card.</span></span></button></div>
    </div><div className="mt-4 flex flex-wrap items-center gap-2"><button type="button" disabled={pending} onClick={() => save("DRAFT")} className="inline-flex items-center gap-2 rounded-xl border border-[var(--br-border)] px-4 py-2.5 text-sm font-bold"><Save size={15} />Save draft</button><button type="button" disabled={pending} onClick={() => save("PUBLISHED")} className="inline-flex items-center gap-2 rounded-xl bg-[var(--br-action)] px-4 py-2.5 text-sm font-bold text-on-dark"><Check size={15} />Publish module</button>{pending ? <span className="text-xs text-[var(--br-text-muted)]">Saving…</span> : null}{message ? <span role="status" className="text-xs font-bold text-[var(--br-action)]">{message}</span> : null}</div>
    {pickerOpen ? <div className="fixed inset-0 z-[100] grid place-items-center bg-black/40 p-4" role="dialog" aria-modal="true" aria-label="Choose module feature image"><section className="flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-[var(--br-border)] bg-surface shadow-2xl"><header className="flex items-start gap-3 border-b border-[var(--br-border)] p-5"><span className="grid size-10 place-items-center rounded-xl bg-[var(--br-brand-soft)] text-[var(--br-brand)]"><ImageIcon size={19} /></span><div className="min-w-0 flex-1"><h2 className="font-bold">Choose feature image</h2><p className="mt-1 text-sm text-[var(--br-text-muted)]">Select an existing image from the Media Library.</p></div><button type="button" onClick={() => setPickerOpen(false)} className="grid size-8 place-items-center rounded-lg text-[var(--br-text-muted)]" aria-label="Close"><X size={17} /></button></header><div className="min-h-0 overflow-y-auto p-4"><label className="relative mb-4 block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--br-text-muted)]" size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search your image library" className="w-full rounded-xl border border-[var(--br-border)] bg-[var(--br-surface-muted)] py-2.5 pl-9 pr-3 text-sm" /></label>{visibleImages.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visibleImages.map((image) => <button type="button" key={image.id} onClick={() => { setFeatureImagePath(image.url); setPickerOpen(false); }} className={`overflow-hidden rounded-xl border text-left transition hover:border-[var(--br-action)] ${selectedImage?.id === image.id ? "border-[var(--br-action)] ring-2 ring-[var(--br-action)]/20" : "border-[var(--br-border)]"}`}><img src={image.url} alt={image.altText || ""} className="aspect-[4/3] w-full object-cover" /><span className="block truncate p-2.5 text-sm font-bold">{image.title || "Untitled image"}</span></button>)}</div> : <p className="rounded-xl border border-dashed border-[var(--br-border)] p-10 text-center text-sm text-[var(--br-text-muted)]">No matching images in the media library.</p>}</div></section></div> : null}
    </section>;
}
