"use client";

import { useRef, useTransition } from "react";
import { CheckCircle2, Clock3, Plus, Trash2 } from "lucide-react";
import { createPersonalTask, deletePersonalTask, updatePracticeTaskStatus } from "@/app/tasks/actions";

export type PracticeTask = { id: string; title: string; description: string | null; task_type: string; priority: string; status: string; due_at: string | null; estimated_minutes: number | null; created_by: string | null; class_id: string | null; classes?: { name?: string | null } | null };

function dueLabel(value: string | null) { return value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : "No due date"; }

export function TaskPlanner({ tasks, editable = false }: { tasks: PracticeTask[]; editable?: boolean }) {
  const [pending, startTransition] = useTransition();
  function update(id: string, status: "TODO" | "IN_PROGRESS" | "COMPLETED") { startTransition(async () => { await updatePracticeTaskStatus(id, status); }); }
  function remove(id: string) { startTransition(async () => { await deletePersonalTask(id); }); }
  return <div className="grid gap-3 md:grid-cols-2">{tasks.map((task) => <article key={task.id} className="flex min-w-0 flex-col gap-3 rounded-[18px] border border-[var(--br-border)] bg-[var(--br-surface)] p-4 shadow-[var(--br-shadow)]"><div className="flex min-w-0 gap-3"><button type="button" disabled={pending} onClick={() => update(task.id, task.status === "COMPLETED" ? "TODO" : "COMPLETED")} className={`grid size-10 shrink-0 place-items-center rounded-xl ${task.status === "COMPLETED" ? "bg-[color-mix(in_srgb,var(--br-success)_12%,var(--br-surface))] text-[var(--br-chart-secondary)]" : "bg-[#F0EDFF] text-[var(--br-brand)]"}`} aria-label={task.status === "COMPLETED" ? "Mark incomplete" : "Mark complete"}>{task.status === "COMPLETED" ? <CheckCircle2 size={19} /> : <Clock3 size={18} />}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className={`break-words font-extrabold ${task.status === "COMPLETED" ? "text-[var(--br-text-muted)] line-through" : "text-[var(--br-text)]"}`}>{task.title}</h3><span className="rounded-full bg-[var(--br-surface-muted)] px-2 py-0.5 text-[10px] font-extrabold text-[var(--br-text-muted)]">{task.task_type.replace("_", " ")}</span>{task.priority === "HIGH" ? <span className="rounded-full bg-[#FFF0ED] px-2 py-0.5 text-[10px] font-extrabold text-[#E66443]">HIGH</span> : null}</div>{task.description ? <p className="mt-1 text-sm leading-6 text-[var(--br-text-muted)]">{task.description}</p> : null}<p className="mt-2 text-xs font-semibold text-[var(--br-text-muted)]">{task.classes?.name ? `${task.classes.name} · ` : ""}{dueLabel(task.due_at)}{task.estimated_minutes ? ` · ${task.estimated_minutes} min` : ""}</p></div></div><div className="flex justify-end gap-2"><button type="button" disabled={pending || task.status === "COMPLETED"} onClick={() => update(task.id, "IN_PROGRESS")} className="rounded-xl border border-[var(--br-border)] px-3 py-2 text-xs font-extrabold text-[var(--br-brand)] disabled:opacity-40">Start</button>{editable && task.created_by && !task.class_id ? <button type="button" disabled={pending} onClick={() => remove(task.id)} className="grid size-9 place-items-center rounded-xl text-[#E66443] hover:bg-[#FFF0ED]" aria-label="Delete task"><Trash2 size={16}/></button> : null}</div></article>)}{!tasks.length ? <div className="grid min-h-44 place-items-center rounded-[18px] border border-dashed border-[var(--br-border)] text-center text-sm text-[var(--br-text-muted)] md:col-span-2">No tasks here yet.</div> : null}</div>;
}

export function NewTaskForm() {
  const [pending, startTransition] = useTransition();
  const formRef = useRef<HTMLFormElement>(null);
  return <form ref={formRef} action={(formData) => startTransition(async () => { const result = await createPersonalTask(formData); if (result.success) formRef.current?.reset(); })} className="rounded-[20px] border border-[var(--br-border)] bg-[var(--br-surface)] p-4 shadow-[var(--br-shadow)]"><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-[#F0EDFF] text-[var(--br-brand)]"><Plus size={18}/></span><h2 className="font-extrabold">Plan a practice task</h2></div><div className="mt-4 grid gap-3"><input name="title" required placeholder="e.g. Review phrasal verbs" className="rounded-xl border border-[var(--br-border)] px-3 py-2.5 text-sm"/><textarea name="description" rows={2} placeholder="A small note for yourself (optional)" className="rounded-xl border border-[var(--br-border)] px-3 py-2.5 text-sm"/><div className="grid gap-3 sm:grid-cols-3"><select name="taskType" className="rounded-xl border border-[var(--br-border)] px-3 py-2.5 text-sm"><option value="SELF_STUDY">Self study</option><option value="PRACTICE">Practice</option><option value="REMINDER">Reminder</option></select><select name="priority" className="rounded-xl border border-[var(--br-border)] px-3 py-2.5 text-sm"><option value="NORMAL">Normal priority</option><option value="HIGH">High priority</option><option value="LOW">Low priority</option></select><input name="estimatedMinutes" type="number" min="1" placeholder="Minutes" className="rounded-xl border border-[var(--br-border)] px-3 py-2.5 text-sm"/></div><input name="dueAt" type="datetime-local" className="rounded-xl border border-[var(--br-border)] px-3 py-2.5 text-sm"/><button disabled={pending} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[var(--br-brand)] px-4 py-2.5 text-sm font-extrabold text-on-dark disabled:opacity-60"><Plus size={16}/> {pending ? "Saving..." : "Add task"}</button></div></form>;
}
