import type { Json } from "@/types/database.types";

export type ActivityReference = {
  type: string;
  category: string;
  prompt: string;
  data: Json;
};

const mcq = {
  prompt: "Choose the best answer.",
  questions: [{ id: 1, text: "She ___ to school every day.", options: { A: "go", B: "goes", C: "going", D: "gone" }, answer: "B" }]
};

const oral = {
  prompt: "Answer the speaking question clearly in 30–60 seconds.",
  allow_self_graded: true,
  allow_ai_feedback: true,
  allow_teacher_review: true,
  questions: [{ id: 1, text: "Introduce yourself. Say your name, where you live, what you do, and one hobby.", model_answer: "My name is Sara. I live in Dhaka, I work as a teacher, and I enjoy gardening.", target_phrases: ["My name is", "I live in", "I work as", "I enjoy"], max_seconds: 60 }]
};

export const ALL_ACTIVITIES_REFERENCE: ActivityReference[] = [
  { type: "MCQ", category: "Core Practice", prompt: "Choose the best answer.", data: mcq },
  { type: "TRUE_FALSE", category: "Core Practice", prompt: "Decide whether the statement is true or false.", data: { prompt: "Decide whether the statement is true or false.", items: [{ statement: "Water freezes at 0°C.", answer: true }] } },
  { type: "GAP_FILL", category: "Core Practice", prompt: "Complete the sentence with the missing word.", data: { prompt: "Complete the sentence with the missing word.", items: [{ level: "sentence", sentence: "I have lived here for ___ years.", answer: "three" }] } },
  { type: "MATCHING", category: "Core Practice", prompt: "Match each word with its meaning.", data: { prompt: "Match each word with its meaning.", questions: [{ id: "1", question_number: 1, question_type: "MATCHING", question_text: "Match each word with its meaning.", options: { a_items: ["rapid", "tiny"], b_items: ["very small", "very fast"] }, correct_answer: [{ a: 1, b: "B" }, { a: 2, b: "A" }] }] } },
  { type: "MULTIPLE_SELECT", category: "Core Practice", prompt: "Choose all the correct answers.", data: { prompt: "Choose all the correct answers.", questions: [{ id: 1, text: "Which are healthy habits?", options: { A: "Sleep well", B: "Skip every meal", C: "Drink water", D: "Never exercise" }, answers: ["A", "C"] }] } },
  { type: "DRAG_DROP", category: "Core Practice", prompt: "Place each item in the correct group.", data: { prompt: "Place each item in the correct group.", targets: ["Fruit", "Vegetable"], items: [{ id: "1", text: "Apple", target: "Fruit" }, { id: "2", text: "Carrot", target: "Vegetable" }] } },
  { type: "CATEGORIZATION", category: "Core Practice", prompt: "Sort each item into the correct category.", data: { prompt: "Sort each item into the correct category.", targets: ["Indoor", "Outdoor"], items: [{ id: "1", text: "Reading", target: "Indoor" }, { id: "2", text: "Cycling", target: "Outdoor" }] } },
  { type: "REORDERING", category: "Core Practice", prompt: "Put the steps in the correct order.", data: { prompt: "Put the steps in the correct order.", questions: [{ level: "sentence", question_text: "Put the morning routine in order.", items: [{ id: "1", text: "I wake up." }, { id: "2", text: "I brush my teeth." }, { id: "3", text: "I eat breakfast." }], correct_order: ["1", "2", "3"] }] } },
  { type: "ERROR_CORRECTION", category: "Core Practice", prompt: "Find and correct the mistake.", data: { prompt: "Find and correct the mistake.", items: [{ mode: "rewrite", text: "She go to work every day.", error_span: "go", correction: "goes", note: "Use the third-person singular form." }] } },
  { type: "SHORT_ANSWER", category: "Core Practice", prompt: "Answer briefly in your own words.", data: { prompt: "Answer briefly in your own words.", questions: [{ id: 1, text: "What do you usually do at the weekend?", sample_answer: "I usually visit my family and read.", min_words: 3, required_words: [], show_required_words: true }] } },
  { type: "SUMMARIZATION", category: "Reading", prompt: "Summarize the passage in your own words.", data: { prompt: "Summarize the passage in your own words.", passage: "Regular exercise improves health, mood, and energy. Even a short daily walk can make a positive difference.", max_words: 25, sample_answer: "Daily exercise supports health and mood." } },
  { type: "INFERENCE_DETECTION", category: "Reading", prompt: "What can we infer from the passage?", data: { prompt: "What can we infer from the passage?", passage: "Mina took an umbrella before leaving home. Dark clouds covered the sky.", questions: [{ id: 1, text: "Why did Mina take an umbrella?", options: { A: "It may rain.", B: "She was going swimming.", C: "The sun was bright.", D: "She lost her bag." }, answer: "A" }] } },
  { type: "HEADINGS_MATCHING", category: "Reading", prompt: "Match each paragraph with the best heading.", data: { prompt: "Match each paragraph with the best heading.", paragraphs: [{ id: "A", text: "Walking is simple and free, and it can improve fitness." }, { id: "B", text: "A balanced breakfast gives learners energy for the day." }], headings: [{ id: "1", text: "The value of walking" }, { id: "2", text: "A useful breakfast" }, { id: "3", text: "Planning a holiday" }], correct_answer: { A: "1", B: "2" } } },
  { type: "SKIM_CHALLENGE", category: "Reading", prompt: "Skim the passage and answer the main-idea question.", data: { prompt: "Skim the passage and answer the main-idea question.", passage: "Community gardens bring neighbours together. People grow food, share skills, and create welcoming public spaces.", time_limit_seconds: 45, allow_passage_toggle: true, question_time_limit_seconds: 0, questions: [{ id: "1", question_text: "What is the passage mainly about?", options: { A: "The benefits of community gardens", B: "How to buy a house", C: "Different sports", D: "A train journey" } }], correct_answer: { "1": "A" } } },
  { type: "PARAPHRASE_ID", category: "Reading", prompt: "Choose the option with the same meaning.", data: { prompt: "Choose the option with the same meaning.", passage: "The meeting was postponed because the manager was ill.", choices: { A: "The meeting happened early.", B: "The meeting was delayed because the manager was sick.", C: "The manager attended a meeting.", D: "The meeting was cancelled forever." }, correct_answer: "B" } },
  { type: "SENTENCE_COMPLETION", category: "Writing", prompt: "Complete the sentence stem.", data: { prompt: "Complete the sentence stem.", sentence_stem: "Although it was raining,", suggested_connectors: ["we", "they"], model_answer: "Although it was raining, we went for a walk.", correct_answer: "we went for a walk.", model_description: "Completes the contrast logically." } },
  { type: "ESSAY_WRITING", category: "Writing", prompt: "Write a short opinion essay.", data: { prompt: "Write a short opinion essay about the value of learning languages.", min_words: 100, max_words: 250, sample_essay: "Learning languages helps people communicate across cultures and discover new ideas.", model_answer: "Learning languages helps people communicate across cultures and discover new ideas.", correct_answer: "Sample essay response", rubric_guidelines: "Check organization, grammar, vocabulary, and support for the main idea." } },
  { type: "EMAIL_LETTER_WRITING", category: "Writing", prompt: "Write a formal email.", data: { prompt: "Write a formal email asking for information about a course.", recipient_role: "Course Director", required_tone: "FORMAL", model_email: "Dear Course Director,\n\nI am writing to ask for information about the next course.\n\nKind regards,\nSam", correct_answer: "Sample formal email" } },
  { type: "TRANSLATION", category: "Writing", prompt: "Translate the sentence into English.", data: { prompt: "Translate the sentence into English.", source_text: "Ella estudia inglés todos los días.", source_language: "Spanish", target_language: "English", acceptable_translations: ["She studies English every day."], correct_answer: "She studies English every day.", grammar_notes: "Use the present simple for a routine." } },
  { type: "PARAPHRASE_PRACTICE", category: "Writing", prompt: "Paraphrase the sentence in your own words.", data: { prompt: "Paraphrase the sentence in your own words.", original_text: "The project was completed on time.", forbidden_phrases: ["completed on time"], model_paraphrase: "The team finished the project by the deadline.", correct_answer: "Sample paraphrase", explanation: "Keep the meaning while changing the wording." } },
  { type: "SENTENCE_COMBINING", category: "Writing", prompt: "Combine the simple sentences.", data: { prompt: "Combine the simple sentences into one fluent sentence.", input_sentences: ["The road was busy.", "We left early."], model_combined_sentence: "Because the road was busy, we left early.", correct_answer: "Because the road was busy, we left early.", explanation: "Use a cause-and-effect connector." } },
  { type: "CREATIVE_WRITING", category: "Writing", prompt: "Write a short creative story.", data: { prompt: "Write a short story using the starter and vocabulary.", story_starter: "When the old door opened...", required_vocabulary: ["whisper", "shadow", "discovery"], model_story: "When the old door opened, a whisper came from the shadow and led to a surprising discovery.", correct_answer: "Creative story response", model_description: "Uses the starter and all required vocabulary." } },
  { type: "PEER_REVIEW_EDITING", category: "Writing", prompt: "Edit the sample peer text and give helpful feedback.", data: { prompt: "Edit the sample peer text and give helpful feedback.", sample_draft: "Yesterday I go to market and buyed apples.", error_focus_areas: ["Past tense", "Articles"], model_edited_draft: "Yesterday I went to the market and bought apples.", correct_answer: "Yesterday I went to the market and bought apples.", model_feedback_comments: "Use irregular past forms and include the article 'the'." } },
  { type: "DIALOGUE_WRITING", category: "Writing", prompt: "Write a short café dialogue.", data: { prompt: "Write a short café dialogue using the scenario and target phrases.", scenario: "A customer ordering food at a café.", speaker_a: "Waiter", speaker_b: "Customer", given_turns: [{ speaker: "Waiter", text: "Hello! What can I get for you?" }], target_phrases: ["recommend", "vegetarian option", "bill"], min_turns: 4, model_dialogue: "Waiter: Hello! What can I get for you?\nCustomer: What do you recommend?\nWaiter: The soup is a good vegetarian option.\nCustomer: Great. Could I have the bill, please?", correct_answer: "Sample dialogue response", rubric_guidelines: "Check turn-taking, politeness, and target phrase use." } },
  { type: "DICTATION", category: "Listening", prompt: "Listen and type exactly what you hear.", data: { prompt: "Listen and type exactly what you hear.", audio_url: "", correct_answer: "Practice makes progress.", hint: "A short encouraging sentence.", ignore_punctuation: true } },
  { type: "LISTEN_AND_SELECT", category: "Listening", prompt: "Listen and choose the matching option.", data: { prompt: "Listen and choose the matching option.", audio_url: "", choices: [{ id: "0", text: "The train is late.", image_url: "" }, { id: "1", text: "The train is early.", image_url: "" }], correct_answer: "0" } },
  { type: "SHADOWING", category: "Listening", prompt: "Listen, repeat, and build fluency.", data: { prompt: "Listen, repeat, and build fluency.", audio_url: "", target_text: "I would like to practise English every day.", correct_answer: "I would like to practise English every day." } },
  { type: "NOTE_TAKING_CHALLENGE", category: "Listening", prompt: "Listen, take notes, and answer the question.", data: { prompt: "Listen, take notes, and answer the question.", media_url: "", audio_url: "", questions: [{ id: "1", text: "What is the main topic?", options: ["Daily exercise", "Cooking", "Travel"] }], correct_answer: { "1": "Daily exercise" } } },
  { type: "SOUND_DISCRIMINATION", category: "Listening", prompt: "Listen and identify the correct word.", data: { prompt: "Listen and identify the correct word.", audio_url: "", pairs: [{ id: "0", word: "ship", phonetic: "/ʃɪp/", audio_url: "" }, { id: "1", word: "sheep", phonetic: "/ʃiːp/", audio_url: "" }], correct_answer: "0" } },
  { type: "LISTEN_AND_GAP_FILL", category: "Listening", prompt: "Listen and complete the transcript.", data: { prompt: "Listen and complete the transcript.", audio_url: "", transcript: "I have been working at this ___ for two years.", answers: ["company"], correct_answer: ["company"] } },
  { type: "TABLE_COMPLETION", category: "Core Practice", prompt: "Complete the missing information in the table.", data: { prompt: "Complete the missing information in the table.", source_type: "NONE", source_url: "", columns: [{ id: "item", label: "Item" }, { id: "detail", label: "Detail" }], rows: [{ id: "row-1", label: "Example", cells: { item: { value: "Example", blank: false }, detail: { value: "Answer", blank: true, mode: "WRITE", answer: "Answer" } } }] } },
  { type: "PRONUNCIATION", category: "Speaking", prompt: "Say each word clearly.", data: { prompt: "Say each word clearly.", level: "word", max_attempts: 3, passage: "", targets: [{ id: "1", text: "comfortable", color: "var(--br-achievement)" }] } },
  { type: "ORAL_RESPONSE", category: "Speaking", prompt: "Answer the speaking question clearly.", data: oral },
  { type: "AI_ROLEPLAY", category: "Speaking", prompt: "Practise ordering food with an AI partner.", data: { prompt: "Practise ordering food with an AI partner.", character: "Café assistant", first_turn: "Hello! Welcome to the café. What would you like today?", target_phrases: ["recommend", "please", "bill"], voice_enabled: true, show_transcript: true } },
  { type: "AI_INTERVIEW", category: "Speaking", prompt: "Answer the interview questions one at a time.", data: { prompt: "Conduct a spoken interview based only on the hidden context.", interview_context: "The learner is practising personal introductions and daily routines.", exact_questions: ["What is your name?", "Where do you live?", "What do you do every day?"], level: "B1", question_count: 3, answer_seconds: 45, character: "AI interviewer", first_turn: "Welcome. I will ask you a few questions. Take your time.", voice_enabled: true, show_transcript: true, save_recordings: false, allow_download: false, attempt_quota: 0, max_seconds_per_attempt: 195 } },
  { type: "LIVE_SPEAK_TRANSLATE", category: "Speaking", prompt: "Speak in Bangla and listen to the English translation.", data: { prompt: "Speak in Bangla and listen to the English translation.", max_seconds_per_attempt: 30, total_seconds_per_learner: 120, show_transcript: true } },
];

export type ContentBlockReference = { blockType: string; content: Json };

export const ALL_CONTENT_BLOCK_REFERENCE: ContentBlockReference[] = [
  { blockType: "HEADING", content: { level: "H2", text: "Speaking focus: clear introductions" } },
  { blockType: "TEXT", content: { body: "Read the question carefully, then choose the answer that completes the sentence." } },
  { blockType: "BULLETS", content: { title: "True or false tips", items: ["Look for key facts.", "Notice words such as always and never.", "Read the full statement before deciding."] } },
  { blockType: "QUOTE", content: { body: "Small steps every day lead to lasting progress.", attribution: "BrenUp practice note" } },
  { blockType: "CALLOUT", content: { title: "Matching tip", body: "Look for meaning, not only for words that look similar.", reveal_hidden: false } },
  { blockType: "IMAGE", content: { path: "", alt: "A visual prompt for healthy habits", caption: "Creator reference: add an image related to the question." } },
  { blockType: "IMAGE_TEXT", content: { image_path: "", image_position: "left", heading: "Sort by meaning", body: "Use the picture and the short explanation to introduce the groups before the learner sorts the items.", alt: "Categorization visual" } },
  { blockType: "IMAGE_ANNOTATION", content: { path: "", alt: "Annotated scene", markers: [{ id: "1", x: 50, y: 45, label: "Example", note: "Add a short annotation." }] } },
  { blockType: "AUDIO", content: { path: "", label: "Listening model" } },
  { blockType: "VIDEO", content: { url: "", title: "Listening video reference" } },
  { blockType: "DIVIDER", content: {} },
  { blockType: "SPACE", content: { height: 40 } },
  { blockType: "VOCABULARY", content: { entries: [{ word: "accurate", pronunciation: "/ˈækjərət/", meaning: "correct and exact", example: "Her answer was accurate." }, { word: "improve", pronunciation: "/ɪmˈpruːv/", meaning: "to become better", example: "Practice helps you improve." }] } },
  { blockType: "GRAMMAR", content: { title: "Past simple reminder", explanation: "Use the past simple for a finished action in the past.", examples: ["I visited my aunt yesterday.", "They studied last night."], notes: "Check the verb form and time expression." } },
  { blockType: "READING", content: { title: "Read before you answer", passage: "Good readers identify the main idea first, then return to the text to find supporting details.", questions: ["What is the main idea?", "Which detail supports it?"] } },
  { blockType: "DIALOGUE", content: { title: "Model conversation", people: [{ id: "a", name: "Waiter", color: "var(--br-brand)" }, { id: "b", name: "Customer", color: "var(--br-success)" }], turns: [{ speaker_id: "a", line: "Welcome. What would you like?" }, { speaker_id: "b", line: "I would like the vegetable soup, please." }] } },
  { blockType: "FLASHCARD", content: { front: "paraphrase", back: "The same meaning expressed with different words." } },
  { blockType: "COMMON_MISTAKE", content: { mistake: "She go to school every day.", correction: "She goes to school every day.", explanation: "Use goes with he, she, and it in the present simple." } },
  { blockType: "CONTRAST_PAIR", content: { title: "Translation contrast", left_label: "Source", left_text: "Ella estudia inglés.", right_label: "Target", right_text: "She studies English." } },
  { blockType: "STEPS", content: { title: "A simple conversation", instruction: "Follow these steps.", steps: [{ title: "Greet", description: "Say hello and be friendly." }, { title: "Ask", description: "Ask your question clearly." }, { title: "Respond", description: "Listen and respond." }, { title: "Thanks", description: "Thank the other person." }] } },
  { blockType: "TABLE", content: { title: "Essay planning", headers: ["Part", "Purpose"], rows: [["Introduction", "Present the topic"], ["Body", "Give reasons and examples"], ["Conclusion", "Summarize the main idea"]] } },
];
