export type CreatorTool = { name: string; description: string; readOnly: boolean; confirmation: boolean };

/** The model-facing vocabulary. Execution remains server-side and allowlisted. */
export const CREATOR_TOOLS: CreatorTool[] = [
  ["find_latest_lesson","Find the most recently created active lesson",true,false], ["search_lessons","Search lessons by natural-language title or topic",true,false], ["resolve_lesson","Resolve a named lesson to an exact database record",true,false], ["read_lesson","Read lesson metadata and structure",true,false], ["read_slides","Read selected slides including blocks and activities",true,false], ["search_courses","Search courses by title",true,false], ["list_course_lessons","List lessons in course order",true,false], ["compare_lessons","Compare two lesson drafts",true,false],
  ["create_course","Create a course draft shell",false,false], ["update_course","Update course metadata",false,false], ["add_course_lesson","Place a lesson in a course",false,false], ["remove_course_lesson","Remove a lesson from a course",false,true], ["reorder_course_lessons","Reorder lessons in a course",false,true],
  ["create_lesson","Create a lesson draft shell",false,false], ["update_lesson","Update lesson metadata",false,false], ["create_slide","Create a slide",false,false], ["update_slide","Update slide fields",false,false], ["delete_slide","Delete a slide",false,true], ["move_slide","Move a slide",false,false], ["copy_slide","Copy a slide",false,false],
  ["list_block_types","Read supported content block schemas",true,false], ["add_content_block","Add a validated content block",false,false], ["update_content_block","Update a content block",false,false], ["delete_content_block","Delete a content block",false,true], ["move_content_block","Move a content block",false,false], ["copy_content_block","Copy a content block",false,false], ["reorder_content_blocks","Reorder blocks",false,false],
  ["list_activity_types","Read supported activity schemas",true,false], ["add_activity","Add a validated activity",false,false], ["update_activity","Update an activity",false,false], ["delete_activity","Delete an activity",false,true], ["move_activity","Move an activity",false,false], ["copy_activity","Copy an activity",false,false], ["validate_activity_answers","Check answer references and correctness",true,false],
  ["preview_changes","Show the proposed draft changes",true,false], ["confirm_changes","Save proposed draft changes",false,false], ["cancel_changes","Discard proposed changes",false,false], ["undo_last_revision","Restore the previous draft revision",false,true], ["copy_lesson_draft","Copy a lesson for editing",false,false],
  ["list_sources","List attached sources",true,false], ["add_source","Attach a source to the conversation",false,false], ["update_source","Edit or disable a source",false,false], ["list_media","List available media assets",true,false], ["attach_media","Attach an existing media asset",false,false], ["check_lesson_quality","Run CEFR, completeness, and missing-media checks",true,false],
].map(([name,description,readOnly,confirmation])=>({name: name as string, description: description as string, readOnly: readOnly as boolean, confirmation: confirmation as boolean}));

export function relevantCreatorTools(goal: string) {
  const lower = goal.toLowerCase();
  const always = new Set(["find_latest_lesson","search_lessons","resolve_lesson","read_lesson","read_slides","preview_changes","confirm_changes","cancel_changes"]);
  const selected = CREATOR_TOOLS.filter(t => always.has(t.name) || (/(course|কোর্স)/.test(lower) && t.name.includes("course")) || (/(slide|স্লাইড)/.test(lower) && t.name.includes("slide")) || (/(block|content|ব্লক|কনটেন্ট)/.test(lower) && t.name.includes("block")) || (/(activit|quiz|activity|অ্যাক্টিভিটি)/.test(lower) && t.name.includes("activit")) || (/(source|সোর্স)/.test(lower) && t.name.includes("source")) || (/(media|image|audio|ভিডিও|ইমেজ)/.test(lower) && t.name.includes("media")));
  return selected.length ? selected : CREATOR_TOOLS.slice(0, 14);
}
