import { ALL_CONTENT_BLOCK_REFERENCE, ALL_ACTIVITIES_REFERENCE } from "@/lib/allActivitiesReference";

/** Compact schema guide generated from the renderer's current references. */
export const LESSON_CONTENT_GUIDE = `BRENUP CONTENT INSERTION MANUAL (AUTHORITATIVE — FOLLOW EXACTLY)
DATABASE MAPPING: a slide is inserted into public.slides. A content block is inserted into public.lesson_blocks with lesson_id, slide_id, position, block_type, content (JSONB). An activity is inserted into public.lesson_slide_activities with lesson_id, slide_id, slide_number, position, activity_type, activity_data (JSONB), needs_review. Questions are NEVER separate rows.
OPERATION FORMAT: first add a slide with {op:"add",entity:"slide",fields:{title:"..."},position:N}. Then add blocks using {op:"add",entity:"block",slide:N,type:"TYPE",content:{...},position:N}. Add an activity using {op:"add",entity:"activity",slide:N,type:"TYPE",content:{...}}. The server creates UUIDs and maps content to the correct database column. Positions are one-based. Use only the exact keys shown below. Never put activity_data inside content or content inside activity_data. Never invent IDs. The slide title is already displayed; do not repeat it as HEADING.
READING EXAMPLE (this is a content block, not an activity): {"op":"add","entity":"block","slide":2,"type":"READING","content":{"title":"A New Neighbourhood","passage":"Maya moved to a new neighbourhood last week. She walked around the streets and met her neighbours. The area was friendly and busy.","questions":["What is the passage mainly about?","Who did Maya meet?"]},"position":1}. Required key: passage. Optional keys: title, questions. The passage must be original and CEFR-appropriate.
VOCABULARY EXAMPLE: {"op":"add","entity":"block","slide":3,"type":"VOCABULARY","content":{"entries":[{"word":"embroidered","pronunciation":"/ɪmˈbrɔɪdərd/","meaning":"decorated with thread","example":"The cloth is beautifully embroidered.","notes":"adjective"}]}}.
MCQ EXAMPLE (this is an activity): {"op":"add","entity":"activity","slide":4,"type":"MCQ","content":{"prompt":"Choose the best answer.","questions":[{"id":1,"text":"Where did Maya go?","options":{"A":"Home","B":"The market","C":"School","D":"The park"},"answer":"B"}]}}. Every MCQ question requires text, options, and answer; answer must be an option key.
For every new block use {op:"add",entity:"block",slide:<number>,type:<BLOCK_TYPE>,content:<exact shape>,position?:<number>}. For every activity use {op:"add",entity:"activity",slide:<number>,type:<ACTIVITY_TYPE>,content:<exact shape>}. To edit, send the complete replacement nested array when changing questions/items. Validate every answer against its choices. Keep open-ended activities needs_review=true. Media slides need framing TEXT immediately before AUDIO/VIDEO and no IMAGE block. Never leave an activity slide without supporting content.
CONTENT BLOCK SCHEMAS (use these keys; extra keys are allowed only when renderer-compatible):
${ALL_CONTENT_BLOCK_REFERENCE.map(x=>`${x.blockType}: ${JSON.stringify(x.content)}`).join("\n")}
ACTIVITY SCHEMAS (questions/items stay inside activity_data; do not create question rows):
${ALL_ACTIVITIES_REFERENCE.map(x=>`${x.type}: ${JSON.stringify(x.data)}`).join("\n")}
Creation sequence: research course and sibling lessons; confirm target draft shell; plan outcomes and slide titles; show synopsis for substantial builds; create slides in order; add blocks in teaching order; add one practice activity where appropriate; validate content and answers; save as DRAFT and report exactly what changed. Do not publish or alter permissions.`;
