"use client";

import { Plus } from "lucide-react";
import { createClass, createClassAssignment, createOrganization } from "./actions";

const field = "w-full rounded-md border border-black/15 bg-white px-3 py-2 text-sm";

export function CreateOrganizationPopup() {
  return <details className="relative"><summary className="inline-flex cursor-pointer list-none items-center gap-2 rounded-lg bg-violetglow px-4 py-2.5 text-sm font-bold text-white shadow-sm [&::-webkit-details-marker]:hidden"><Plus size={16} /> New organization</summary><form action={createOrganization} className="absolute right-0 z-30 mt-2 grid w-[min(92vw,390px)] gap-3 rounded-xl border border-black/10 bg-white p-4 shadow-xl"><p className="text-sm font-bold">Create organization</p><input name="name" required placeholder="School or organization name" className={field} /><input name="brandName" placeholder="Display name (optional)" className={field} /><textarea name="description" rows={3} placeholder="Short description" className={field} /><button className="w-fit rounded-md bg-dark px-3 py-2 text-sm font-semibold text-white">Create organization</button></form></details>;
}

export function OrganizationWorkspacePopups({ organizationId, classes, teachers, courses, lessons, quizzes }: { organizationId: string; classes: Array<{ id: string; name: string }>; teachers: Array<{ id: string; label: string }>; courses: Array<{ id: string; title: string }>; lessons: Array<{ id: string; title: string }>; quizzes: Array<{ id: string; title: string }> }) {
  return <div className="flex flex-wrap gap-2"><details className="relative"><summary className="inline-flex cursor-pointer list-none items-center gap-2 rounded-lg bg-violetglow px-3 py-2 text-sm font-bold text-white [&::-webkit-details-marker]:hidden"><Plus size={15} /> Add class</summary><form action={createClass} className="absolute right-0 z-30 mt-2 grid w-[min(92vw,360px)] gap-3 rounded-xl border border-black/10 bg-white p-4 shadow-xl"><input name="organizationId" type="hidden" value={organizationId} /><input name="name" required placeholder="Class name" className={field} /><select name="teacherId" className={field}><option value="">No teacher assigned</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.label}</option>)}</select><input name="level" placeholder="Level, e.g. B1" className={field} /><textarea name="description" rows={3} placeholder="Description (optional)" className={field} /><button className="w-fit rounded-md bg-dark px-3 py-2 text-sm font-semibold text-white">Create class</button></form></details><details className="relative"><summary className="inline-flex cursor-pointer list-none items-center gap-2 rounded-lg border border-black/15 bg-white px-3 py-2 text-sm font-bold hover:bg-black/5 [&::-webkit-details-marker]:hidden"><Plus size={15} /> Add assignment</summary><form action={createClassAssignment} className="absolute right-0 z-30 mt-2 grid w-[min(92vw,420px)] gap-3 rounded-xl border border-black/10 bg-white p-4 shadow-xl"><select name="classId" required className={field}><option value="">Choose class...</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="itemType" className={field}><option value="COURSE">Course</option><option value="LESSON">Standalone lesson</option><option value="QUIZ">Standalone quiz</option><option value="LEVEL_TEST">Level test</option></select><select name="courseId" className={field}><option value="">Choose course...</option>{courses.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select name="lessonId" className={field}><option value="">Choose standalone lesson...</option>{lessons.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><select name="quizId" className={field}><option value="">Choose standalone quiz...</option>{quizzes.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input name="title" placeholder="Assignment title (optional)" className={field} /><div className="grid grid-cols-2 gap-3"><input name="dueAt" type="datetime-local" className={field} /><input name="requiredScore" type="number" min="0" max="100" placeholder="Target score %" className={field} /></div><button className="w-fit rounded-md bg-dark px-3 py-2 text-sm font-semibold text-white">Create assignment</button></form></details></div>;
}
