import { requireAdmin } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { savePracticeBillingSettings } from "@/app/activities/actions";

export const dynamic = "force-dynamic";

export default async function PracticeBillingSettingsPage() {
  await requireAdmin();
  const { data } = await (createAdminClient() as any).from("practice_billing_settings").select("*").eq("id", true).maybeSingle();
  return <main className="mx-auto max-w-3xl space-y-5"><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-[var(--br-action)]">Practice Library</p><h1 className="mt-1 text-2xl font-extrabold">Billing settings</h1><p className="mt-2 text-sm text-[var(--br-text-muted)]">Set the optional course add-on and subscription prices. Leave a price blank to keep that option unavailable.</p></div><form action={savePracticeBillingSettings} className="grid gap-4 rounded-2xl border border-[var(--br-border)] bg-surface p-5 sm:grid-cols-2"><label className="text-sm font-bold">Course add-on (BDT)<input name="addonPriceBdt" type="number" min="0" step="1" defaultValue={data?.addon_price_bdt ?? ""} className="mt-1 w-full rounded-xl border border-[var(--br-border)] px-3 py-2.5 font-normal" /></label><label className="text-sm font-bold">1 month (BDT)<input name="monthlyPriceBdt" type="number" min="0" step="1" defaultValue={data?.monthly_price_bdt ?? ""} className="mt-1 w-full rounded-xl border border-[var(--br-border)] px-3 py-2.5 font-normal" /></label><label className="text-sm font-bold">6 months (BDT)<input name="sixMonthPriceBdt" type="number" min="0" step="1" defaultValue={data?.six_month_price_bdt ?? ""} className="mt-1 w-full rounded-xl border border-[var(--br-border)] px-3 py-2.5 font-normal" /></label><label className="text-sm font-bold">12 months (BDT)<input name="annualPriceBdt" type="number" min="0" step="1" defaultValue={data?.annual_price_bdt ?? ""} className="mt-1 w-full rounded-xl border border-[var(--br-border)] px-3 py-2.5 font-normal" /></label><label className="text-sm font-bold sm:col-span-2">Payment instructions<textarea name="paymentInstructions" rows={5} defaultValue={data?.payment_instructions ?? ""} className="mt-1 w-full rounded-xl border border-[var(--br-border)] px-3 py-2.5 font-normal" /></label><button className="w-fit rounded-xl bg-[var(--br-action)] px-4 py-2.5 text-sm font-extrabold text-on-dark">Save billing settings</button></form></main>;
}
