import Link from "next/link";
import { ArrowLeft, Link2, UsersRound } from "lucide-react";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireSchoolWorkspace } from "@/lib/schoolAccess";
import { GuardianInviteButton } from "../GuardianInviteButton";

export default async function SchoolGuardiansPage({ searchParams }: { searchParams: Promise<{ org?: string }> }) {
  const session = await requireSchoolWorkspace(); const { org } = await searchParams; const admin = createAdminClient();
  let query = admin.from("organizations").select("id,name,brand_name").order("name"); if (session.organizationIds) query = query.in("id", session.organizationIds);
  const { data: organizations } = await query; const organization = (organizations ?? []).find((item) => item.id === org) ?? organizations?.[0] ?? null;
  if (!organization) return <main><h1 className="text-2xl font-semibold">Guardian access</h1></main>;
  const { data: classes } = await admin.from("classes").select("id,name").eq("organization_id", organization.id); const classIds = (classes ?? []).map((row) => row.id);
  const { data: classMembers } = classIds.length ? await admin.from("class_members").select("user_id,class_id").in("class_id", classIds).eq("role", "STUDENT") : { data: [] };
  const learnerIds = [...new Set((classMembers ?? []).map((row) => row.user_id))]; const [{ data: learners }, { data: links }] = await Promise.all([learnerIds.length ? admin.from("profiles").select("id,full_name,first_name,last_name,cefr_level").in("id", learnerIds).order("full_name") : Promise.resolve({ data: [] }), learnerIds.length ? admin.from("guardian_links").select("learner_id,guardian_id,created_at").in("learner_id", learnerIds) : Promise.resolve({ data: [] })]);
  const classNames = new Map((classes ?? []).map((row) => [row.id, row.name])); const learnerClasses = new Map<string, string[]>(); for (const member of classMembers ?? []) learnerClasses.set(member.user_id, [...(learnerClasses.get(member.user_id) ?? []), classNames.get(member.class_id) ?? "Class"]);
  return <main className="min-w-0"><Link href={`/admin/school?org=${organization.id}`} className="inline-flex items-center gap-1.5 text-sm font-semibold text-black/55 hover:text-violetglow"><ArrowLeft size={15} /> School workspace</Link><div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wide text-violetglow">{organization.brand_name || organization.name}</p><h1 className="mt-1 text-2xl font-semibold sm:text-3xl">Guardian access</h1><p className="mt-2 max-w-2xl text-sm text-black/60">Create a private invite link for one guardian per learner. Guardians get a read-only progress view and cannot access the school workspace.</p></div><section className="relative mt-6 overflow-visible rounded-xl border border-black/10 bg-white shadow-sm"><div className="divide-y divide-black/10">{(learners ?? []).map((learner) => { const name = learner.full_name?.trim() || [learner.first_name, learner.last_name].filter(Boolean).join(" ") || "Learner"; const linked = (links ?? []).find((link) => link.learner_id === learner.id); return <article key={learner.id} className="relative flex flex-wrap items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="font-semibold">{name}</p><p className="mt-1 text-xs text-black/50">{(learnerClasses.get(learner.id) ?? []).join(", ") || "No class"}{learner.cefr_level ? ` · ${learner.cefr_level}` : ""}</p></div>{linked ? <span className="rounded-full bg-moss/10 px-3 py-1.5 text-xs font-bold text-moss">Guardian linked</span> : <GuardianInviteButton organizationId={organization.id} learnerId={learner.id} learnerName={name} />}</article>; })}{!(learners ?? []).length ? <div className="grid min-h-52 place-items-center p-6 text-center"><div><UsersRound className="mx-auto text-black/25" size={28} /><p className="mt-3 text-sm text-black/55">Add learners to classes before inviting guardians.</p></div></div> : null}</div></section><div className="mt-5 flex gap-3 rounded-xl border border-violetglow/15 bg-violetglow/[.04] p-4 text-sm text-black/60"><Link2 className="shrink-0 text-violetglow" size={18} /><p>Invite links expire after 30 days and work only for the email address entered by the school.</p></div></main>;
}
