import Link from "next/link";
import { Building2, GraduationCap, Plus, UsersRound } from "lucide-react";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireSchoolWorkspace } from "@/lib/schoolAccess";
import { createSchoolClass, updateSchoolBranding } from "./actions";
import { SchoolMemberForm } from "./SchoolMemberForm";

export default async function SchoolWorkspacePage({ searchParams }: { searchParams: Promise<{ org?: string }> }) {
  const session = await requireSchoolWorkspace();
  const { org } = await searchParams;
  const admin = createAdminClient();
  let organizationsQuery = admin.from("organizations").select("id,name,brand_name,logo_url,accent_color,description").order("name");
  if (session.organizationIds) organizationsQuery = organizationsQuery.in("id", session.organizationIds);
  const { data: organizations } = await organizationsQuery;
  const organization = (organizations ?? []).find((row) => row.id === org) ?? organizations?.[0] ?? null;
  if (!organization) return <main><h1 className="text-2xl font-semibold">School workspace</h1><p className="mt-2 text-sm text-black/60">Your account is not yet linked to a school. Ask a platform admin to add you as a School Admin.</p></main>;

  const [{ data: members }, { data: classes }, { data: assignments }] = await Promise.all([
    admin.from("organization_members").select("user_id,role,created_at").eq("organization_id", organization.id).order("created_at", { ascending: false }),
    admin.from("classes").select("id,name,level,status,teacher_id,description").eq("organization_id", organization.id).order("created_at", { ascending: false }),
    admin.from("class_assignments").select("id,class_id").in("class_id", (await admin.from("classes").select("id").eq("organization_id", organization.id)).data?.map((row) => row.id) ?? []),
  ]);
  const profileIds = [...new Set((members ?? []).map((row) => row.user_id).concat((classes ?? []).map((row) => row.teacher_id).filter((id): id is string => Boolean(id))))];
  const { data: profiles } = profileIds.length ? await admin.from("profiles").select("id,full_name,first_name,last_name").in("id", profileIds) : { data: [] };
  const names = new Map((profiles ?? []).map((row) => [row.id, row.full_name?.trim() || [row.first_name, row.last_name].filter(Boolean).join(" ") || "BrenUp member"]));
  const teachers = (members ?? []).filter((row) => row.role === "TEACHER");
  const learnerCount = (members ?? []).filter((row) => row.role === "STUDENT").length;
  const assignmentCount = assignments?.length ?? 0;

  return <main className="min-w-0">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-moss">School administration</p><h1 className="mt-1 text-2xl font-semibold sm:text-3xl">{organization.brand_name || organization.name}</h1><p className="mt-2 text-sm text-black/60">Your school’s people, classes, learning operations, and identity.</p></div>{(organizations?.length ?? 0) > 1 ? <div className="flex flex-wrap gap-2">{organizations?.map((item) => <Link key={item.id} href={`/admin/school?org=${item.id}`} className={`rounded-md px-3 py-2 text-xs font-semibold ${item.id === organization.id ? "bg-ink text-white" : "border border-black/15 hover:bg-black/5"}`}>{item.brand_name || item.name}</Link>)}</div> : null}</div>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Teachers" value={teachers.length} /><Metric label="Learners" value={learnerCount} /><Metric label="Active classes" value={(classes ?? []).filter((row) => row.status === "ACTIVE").length} /><Metric label="Assignments" value={assignmentCount} /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-5"><section className="rounded-xl border border-black/10 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><UsersRound size={18} className="text-moss" /><h2 className="font-semibold">School members</h2></div><p className="mt-1 text-sm text-black/55">Add existing BrenUp accounts. Invite new teachers from the platform Users page.</p><SchoolMemberForm organizationId={organization.id} /><div className="mt-5 divide-y divide-black/10">{(members ?? []).map((member) => <div key={member.user_id} className="flex items-center justify-between gap-3 py-3"><p className="min-w-0 truncate text-sm font-semibold">{names.get(member.user_id) ?? "BrenUp member"}</p><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold text-slate-600">{member.role.replace("_", " ")}</span></div>)}</div></section><section className="rounded-xl border border-black/10 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><GraduationCap size={18} className="text-moss" /><h2 className="font-semibold">Classes</h2></div><Link href="/admin/classes" className="text-xs font-bold text-violetglow hover:underline">Open class workspace</Link></div><div className="mt-4 divide-y divide-black/10">{(classes ?? []).map((klass) => <Link key={klass.id} href={`/admin/classes/${klass.id}`} className="flex items-center justify-between gap-3 py-3 hover:bg-slate-50"><div className="min-w-0"><p className="truncate font-semibold">{klass.name}</p><p className="mt-1 text-xs text-black/50">{klass.level || "All levels"} · {klass.teacher_id ? names.get(klass.teacher_id) || "Teacher" : "No teacher assigned"}</p></div><span className="rounded-full bg-moss/10 px-2.5 py-1 text-[11px] font-bold text-moss">{klass.status}</span></Link>)}{!classes?.length ? <p className="py-6 text-center text-sm text-black/55">No classes yet.</p> : null}</div></section></div>
      <aside className="space-y-5"><form action={createSchoolClass.bind(null, organization.id)} className="rounded-xl border border-black/10 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Plus size={18} className="text-moss" /><h2 className="font-semibold">Create class</h2></div><div className="mt-4 grid gap-3"><input name="name" required placeholder="Class name" className="rounded-md border border-black/15 px-3 py-2 text-sm" /><input name="level" placeholder="Level, e.g. B1" className="rounded-md border border-black/15 px-3 py-2 text-sm" /><select name="teacherId" className="rounded-md border border-black/15 px-3 py-2 text-sm"><option value="">No teacher assigned</option>{teachers.map((teacher) => <option key={teacher.user_id} value={teacher.user_id}>{names.get(teacher.user_id) || "Teacher"}</option>)}</select><textarea name="description" rows={3} placeholder="Description (optional)" className="rounded-md border border-black/15 px-3 py-2 text-sm" /><button className="w-fit rounded-md bg-ink px-3 py-2 text-sm font-semibold text-white">Create class</button></div></form><form action={updateSchoolBranding.bind(null, organization.id)} className="rounded-xl border border-black/10 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Building2 size={18} className="text-moss" /><h2 className="font-semibold">School identity</h2></div><div className="mt-4 grid gap-3"><input name="brandName" defaultValue={organization.brand_name ?? ""} placeholder="Display name" className="rounded-md border border-black/15 px-3 py-2 text-sm" /><input name="logoUrl" type="url" defaultValue={organization.logo_url ?? ""} placeholder="Logo image URL" className="rounded-md border border-black/15 px-3 py-2 text-sm" /><label className="text-xs font-semibold text-black/55">Accent color <input name="accentColor" type="color" defaultValue={organization.accent_color ?? "#6C3BFF"} className="ml-2 h-8 w-12 rounded border border-black/15 bg-white p-0.5 align-middle" /></label><button className="w-fit rounded-md border border-black/15 px-3 py-2 text-sm font-semibold hover:bg-black/5">Save identity</button></div></form></aside></section>
  </main>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-black/10 bg-white p-4 shadow-sm"><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs font-semibold uppercase tracking-wide text-black/45">{label}</p></div>; }
