"use client";

import { useState, useTransition } from "react";
import { UserMinus, UsersRound } from "lucide-react";
import { removeSchoolMember, reassignSchoolClassTeacher } from "./actions";
import { SchoolMemberForm } from "./SchoolMemberForm";

type Member = { id: string; name: string; role: "TEACHER" | "STUDENT"; assignedClassIds: string[] };
type ClassItem = { id: string; name: string; teacherId: string | null };

export function SchoolMembersPanel({ organizationId, members, classes, teachers }: { organizationId: string; members: Member[]; classes: ClassItem[]; teachers: Array<{ id: string; name: string }> }) {
  const [message, setMessage] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const teacherMembers = members.filter((member) => member.role === "TEACHER");
  return <section className="rounded-xl border border-[var(--br-border)] bg-surface p-5 shadow-sm"><div className="flex items-center gap-2"><UsersRound size={18} className="text-violetglow" /><h2 className="font-semibold">School members</h2></div><SchoolMemberForm organizationId={organizationId} /><div className="mt-4 divide-y divide-black/10">{members.map((member) => <article key={member.id} className="py-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-semibold">{member.name}</p><p className="mt-0.5 text-xs text-[var(--br-text-muted)]">{member.role === "TEACHER" ? `${member.assignedClassIds.length} assigned classes` : "Learner"}</p></div><button type="button" disabled={pending} onClick={() => { if (!window.confirm(`Remove ${member.name} from this school?`)) return; startTransition(async () => { const result = await removeSchoolMember(organizationId, member.id); setMessage(result.success ? "Member removed." : result.error ?? "Could not remove member."); }); }} className="inline-flex items-center gap-1.5 rounded-md px-2 py-1.5 text-xs font-semibold text-red-600 hover:bg-red-50 disabled:opacity-50"><UserMinus size={13} /> Remove</button></div>{member.role === "TEACHER" && member.assignedClassIds.length ? <div className="mt-2 grid gap-2">{classes.filter((klass) => klass.teacherId === member.id).map((klass) => <form key={klass.id} onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; startTransition(async () => { const result = await reassignSchoolClassTeacher(organizationId, klass.id, new FormData(form)); setMessage(result.success ? `${klass.name} updated.` : result.error ?? "Could not update class."); }); }} className="flex items-center gap-2 rounded-lg bg-surface-muted p-2"><span className="min-w-0 flex-1 truncate text-xs font-medium">{klass.name}</span><select name="teacherId" defaultValue={member.id} className="max-w-36 rounded border border-[var(--br-border)] bg-surface px-2 py-1 text-xs"><option value="">Unassign</option>{teacherMembers.filter((teacher) => teacher.id !== member.id).map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select><button className="text-xs font-bold text-violetglow">Save</button></form>)}</div> : null}</article>)}{!members.length ? <p className="py-5 text-center text-sm text-[var(--br-text-muted)]">Add teachers and learners to begin.</p> : null}</div>{message ? <p className="mt-3 text-xs font-semibold text-[var(--br-text-muted)]">{message}</p> : null}</section>;
}
