import Link from "next/link";
import { ArrowLeft, CalendarDays, Radio } from "lucide-react";
import { requireStaff, isPlatformAdmin } from "@/lib/auth";
import { getSchoolAdminOrganizationIds } from "@/lib/schoolAccess";
import { createAdminClient } from "@/lib/supabase/admin";

export default async function LiveClassCalendarPage() {
  const { user, profile } = await requireStaff(); const admin = createAdminClient(); let query = admin.from("classes").select("id,name,teacher_id,organization_id").eq("status", "ACTIVE");
  if (!isPlatformAdmin(profile?.role)) { const orgIds = profile?.role === "SCHOOL_ADMIN" ? await getSchoolAdminOrganizationIds(user.id) : []; query = orgIds.length ? query.or(`teacher_id.eq.${user.id},created_by.eq.${user.id},organization_id.in.(${orgIds.join(",")})`) : query.or(`teacher_id.eq.${user.id},created_by.eq.${user.id}`); }
  const { data: classes } = await query; const ids = (classes ?? []).map((item) => item.id); const { data: sessions } = ids.length ? await admin.from("live_sessions").select("id,class_id,title,status,scheduled_at,duration_minutes").in("class_id", ids).not("scheduled_at", "is", null).order("scheduled_at") : { data: [] }; const names = new Map((classes ?? []).map((item) => [item.id, item.name])); const groups = new Map<string, typeof sessions>(); for (const item of sessions ?? []) { const date = new Date(item.scheduled_at!).toLocaleDateString(undefined, { weekday: "long", month: "long", day: "numeric" }); groups.set(date, [...(groups.get(date) ?? []), item]); }
  return <main className="min-w-0"><Link href="/admin/live-classes" className="inline-flex items-center gap-1.5 text-sm font-bold text-[var(--br-chart-primary)]"><ArrowLeft size={15} /> Live classes</Link><header className="mt-4 rounded-[20px] bg-gradient-to-br from-[#211075] to-[var(--br-chart-primary)] px-5 py-5 text-white"><p className="text-xs font-bold uppercase tracking-[.14em] text-white/65">Live classroom</p><h1 className="mt-1 text-2xl font-extrabold">Class calendar</h1><p className="mt-1 text-sm text-white/75">A clean view of every scheduled BrenUp session.</p></header><div className="mt-5 space-y-5">{[...groups.entries()].map(([date, entries]) => <section key={date}><h2 className="mb-2 text-sm font-extrabold text-[#4B4F68]">{date}</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(entries ?? []).map((item) => <Link key={item.id} href={`/admin/live-classes/${item.id}`} className="rounded-xl border border-[var(--br-surface-strong)] bg-white p-4 shadow-sm hover:border-[var(--br-chart-primary)]/25"><div className="flex items-center justify-between gap-2"><span className="grid size-9 place-items-center rounded-lg bg-[var(--br-surface-muted)] text-[var(--br-chart-primary)]">{item.status === "LIVE" ? <Radio size={16} /> : <CalendarDays size={16} />}</span><span className="text-xs font-bold text-[var(--br-text-muted)]">{new Date(item.scheduled_at!).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</span></div><h3 className="mt-3 font-extrabold">{item.title}</h3><p className="mt-1 text-xs text-[var(--br-text-muted)]">{names.get(item.class_id)} · {item.duration_minutes} min</p></Link>)}</div></section>)}{!sessions?.length ? <div className="rounded-xl border border-dashed border-[#D9DCE9] bg-white p-10 text-center text-sm font-semibold text-[var(--br-text-muted)]">No scheduled live classes yet.</div> : null}</div></main>;
}
