-- Expand the seven mockup anchor words with curated, fully-described
-- vocabulary. Every spoke below is a real Wordverse relationship.
insert into public.wordverse_words (
  slug, word, pronunciation, word_class, cefr_level, definition, examples,
  collocations, synonyms, antonyms, word_family, grammar_patterns,
  common_mistakes, register, frequency_score, origin, topic_id
)
select
  seed.slug, seed.word, seed.pronunciation, seed.word_class, seed.cefr_level,
  seed.definition, seed.examples::jsonb, seed.collocations::jsonb,
  seed.synonyms::jsonb, seed.antonyms::jsonb, seed.word_family::jsonb,
  seed.grammar_patterns::jsonb, seed.common_mistakes::jsonb, seed.register,
  seed.frequency_score, seed.origin, topic.id
from (values
  ('cost','cost','/kɒst/','noun','A2','the amount of money needed to buy or do something','["The cost of repairs was higher than expected."]','["the cost of living","reduce costs"]','["price","expense"]','["benefit"]','["costly","cost-effective"]','["the cost of something","cost someone money"]','["Cost is not normally used with a person as the object when meaning price."]','neutral',98,'From Latin constare, to stand firm','travel'),
  ('value','value','/ˈvæljuː/','noun','B1','the amount that something is worth or the usefulness it has','["This course offers excellent value."]','["good value","value for money"]','["worth","importance"]','["worthlessness"]','["valuable","valuate"]','["the value of something","value something at a price"]','["Value and price are related but not identical."]','neutral',94,'From Latin valere, to be strong','work'),
  ('rate','rate','/reɪt/','noun','B1','a measurement or amount compared with another amount','["The exchange rate changed overnight."]','["interest rate","at a high rate"]','["level","charge"]','["constant"]','["rateable","rating"]','["rate something at a level","at a rate of"]','["Use rate for a measured amount, not every kind of price."]','neutral',91,'From Latin ratus, fixed or settled','work'),
  ('fee','fee','/fiː/','noun','B1','an amount of money paid for a service','["There is no extra fee for delivery."]','["entrance fee","legal fee"]','["charge","payment"]','["refund"]','["feeless"]','["a fee for something"]','["Fee usually refers to a service, while price refers to a product."]','neutral',87,'From Old English feoh, property or money','work'),
  ('charge','charge','/tʃɑːdʒ/','noun','B1','an amount of money asked for a service or product','["The hotel adds a service charge."]','["service charge","charge a fee"]','["fee","cost"]','["credit"]','["chargeable","charger"]','["charge someone for something"]','["Do not confuse charge with cost when describing who pays."]','neutral',93,'From Old French chargier, to load','work'),
  ('expense','expense','/ɪkˈspens/','noun','B1','money spent on something','["Travel expenses will be reimbursed."]','["business expenses","cover expenses"]','["cost","outlay"]','["income"]','["expensive","inexpensive"]','["expense on something","at someone’s expense"]','["Expense is countable when referring to separate costs."]','neutral',89,'From Latin expendere, to weigh out','work'),
  ('worth','worth','/wɜːθ/','noun','B1','the value of something in money or usefulness','["The painting is worth thousands of dollars."]','["net worth","worth the effort"]','["value","merit"]','["worthlessness"]','["worthy","worthwhile"]','["be worth doing","be worth a price"]','["Use worth with an adjective or -ing form, not usually to + verb."]','neutral',92,'From Old English weorþ, value','society'),
  ('offer','offer','/ˈɒfə/','noun','A2','a proposal to give or do something, often at a particular price','["They accepted our offer."]','["special offer","make an offer"]','["proposal","bid"]','["refusal"]','["offer","offering"]','["offer to do something","offer something to someone"]','["Offer can mean both a proposal and a reduced price."]','neutral',95,'From Latin offerre, to present','work'),
  ('arrangement','arrangement','/əˈreɪndʒmənt/','noun','B1','an agreement or plan made between people','["We made an arrangement with the supplier."]','["make arrangements","an arrangement with someone"]','["agreement","plan"]','["disorder"]','["arrange","rearrange"]','["an arrangement to do something"]','["Arrangement is usually countable when it means an agreement."]','neutral',84,'From French arranger, to put in order','communication'),
  ('negotiation','negotiation','/nɪˌɡəʊʃiˈeɪʃən/','noun','B1','a formal discussion to reach an agreement','["The negotiations lasted three days."]','["peace negotiations","enter negotiations"]','["bargaining","discussion"]','["dictation"]','["negotiate","negotiator","negotiable"]','["negotiation between parties","negotiation over a price"]','["Negotiation is often used in the plural for a process."]','formal',82,'From Latin negotiari, to carry on business','work'),
  ('transaction','transaction','/trænˈzækʃən/','noun','B2','an occasion when money or goods are exchanged','["The transaction was completed securely."]','["financial transaction","complete a transaction"]','["deal","exchange"]','["retention"]','["transact","transactional"]','["a transaction between parties"]','["Transaction is more formal than purchase in many contexts."]','formal',80,'From Latin transigere, to drive through','work'),
  ('clause','clause','/klɔːz/','noun','B2','a separate part of a legal document or agreement','["The contract contains a cancellation clause."]','["contract clause","include a clause"]','["condition","provision"]','["omission"]','["clausal"]','["a clause in a contract"]','["A clause is part of a document, not the whole agreement."]','formal',76,'From Latin clausula, a closing section','work'),
  ('obligation','obligation','/ˌɒblɪˈɡeɪʃən/','noun','B2','a duty to do something because of a rule or agreement','["The contract creates an obligation to pay."]','["legal obligation","meet an obligation"]','["duty","commitment"]','["choice"]','["oblige","obligatory"]','["an obligation to do something"]','["An obligation can be legal, moral, or financial."]','formal',78,'From Latin obligare, to bind','work'),
  ('signature','signature','/ˈsɪɡnətʃə/','noun','B1','a person’s name written to show agreement or approval','["The agreement needs your signature."]','["electronic signature","sign a signature"]','["autograph","approval"]','["rejection"]','["sign","signed"]','["signature on a document","signature of a person"]','["Use sign a document, not sign a signature, in most contexts."]','formal',83,'From Latin signare, to mark','work'),
  ('renewal','renewal','/rɪˈnjuːəl/','noun','B2','the act of extending an agreement or period of validity','["The lease is due for renewal next month."]','["contract renewal","annual renewal"]','["extension","continuation"]','["cancellation"]','["renew","renewable"]','["renewal of a contract"]','["Renewal extends an existing agreement; it does not create a first agreement."]','formal',72,'From Latin renovare, to make new again','work'),
  ('condition','condition','/kənˈdɪʃən/','noun','B1','a rule or fact that must exist before something else happens','["Payment is a condition of delivery."]','["terms and conditions","on condition that"]','["requirement","circumstance"]','["result"]','["conditional","conditioned"]','["a condition of something","on condition that"]','["Condition can mean a requirement or a state of being."]','neutral',95,'From Latin condicio, agreement or situation','work'),
  ('provision','provision','/prəˈvɪʒən/','noun','B2','a condition or arrangement in a legal document','["The provision allows either side to cancel."]','["legal provision","make provision for"]','["clause","measure"]','["neglect"]','["provide","provisional"]','["a provision for something"]','["Provision is formal when it means a clause or arrangement."]','formal',77,'From Latin providere, to foresee','work'),
  ('stipulation','stipulation','/ˌstɪpjʊˈleɪʃən/','noun','C1','a specific condition that is part of an agreement','["The main stipulation was early payment."]','["contractual stipulation","under a stipulation"]','["condition","requirement"]','["option"]','["stipulate","stipulated"]','["a stipulation that something happen"]','["Stipulation is formal and usually refers to a precise condition."]','formal',61,'From Latin stipulari, to demand a guarantee','work'),
  ('steal','steal','/stiːl/','noun','B1','something bought for much less than it is worth','["That jacket was a steal at twenty dollars."]','["a real steal","get a steal"]','["bargain","deal"]','["rip-off"]','["steal","stolen"]','["a steal at a price"]','["As a noun, steal is informal and does not mean theft in this expression."]','informal',86,'From Old English stelan, to take secretly','travel'),
  ('trade','trade','/treɪd/','noun','B1','the activity of buying, selling, or exchanging goods','["International trade supports many jobs."]','["trade agreement","trade in goods"]','["commerce","business"]','["boycott"]','["trader","trading","tradeable"]','["trade with someone","trade something for something"]','["Trade can describe an activity, an industry, or an exchange."]','neutral',96,'From Middle English trade, a path or course','work'),
  ('reduction','reduction','/rɪˈdʌkʃən/','noun','B1','a decrease in size, amount, or price','["The store offered a reduction on winter clothes."]','["price reduction","cost reduction"]','["decrease","discount"]','["increase"]','["reduce","reduced"]','["a reduction in price","reduce something by a percentage"]','["Use reduction in for the amount reduced, not reduction of in every context."]','neutral',90,'From Latin reducere, to lead back','travel'),
  ('rebate','rebate','/ˈriːbeɪt/','noun','B2','money returned after a purchase or payment','["Customers can claim a tax rebate."]','["cash rebate","rebate on a purchase"]','["refund","discount"]','["surcharge"]','["rebate"]','["a rebate on something"]','["A rebate is usually returned after payment, unlike an instant discount."]','formal',69,'From Old French rabattre, to beat back','travel'),
  ('markdown','markdown','/ˈmɑːkdaʊn/','noun','B2','a reduction in the selling price of something','["The shoes were a substantial markdown."]','["seasonal markdown","mark something down"]','["reduction","discount"]','["markup"]','["mark down","marked-down"]','["a markdown on an item"]','["Markdown is especially common in retail contexts."]','neutral',65,'From the phrase mark down, to lower a marked price','travel'),
  ('sale','sale','/seɪl/','noun','A2','a period when goods are offered at lower prices','["The store is having a summer sale."]','["on sale","annual sale"]','["discount","promotion"]','["purchase"]','["sell","seller","sales"]','["for sale","on sale"]','["For sale means available to buy; on sale often means reduced in price."]','neutral',97,'From Old English sala, a sale or exchange','travel'),
  ('saving','saving','/ˈseɪvɪŋ/','noun','B1','an amount of money not spent or a reduction in cost','["The promotion gives customers a saving of ten percent."]','["cost saving","make savings"]','["economy","discount"]','["waste"]','["save","saver"]','["a saving of money","save money on something"]','["Saving is often plural when referring to money kept back."]','neutral',88,'From Old French sauver, to protect','travel'),
  ('consensus','consensus','/kənˈsensəs/','noun','B2','general agreement among a group of people','["The committee reached a consensus."]','["reach a consensus","broad consensus"]','["agreement","accord"]','["disagreement"]','["consensual"]','["consensus among people","consensus on an issue"]','["Consensus is normally uncountable and does not need an article after reach."]','formal',80,'From Latin consensus, agreement or feeling together','communication'),
  ('accord','accord','/əˈkɔːd/','noun','B2','a formal agreement between people or groups','["The two countries signed an accord."]','["peace accord","in accord with"]','["agreement","treaty"]','["conflict"]','["accordingly","accordance"]','["an accord between parties","in accord with something"]','["Accord is more formal than agreement in many contexts."]','formal',73,'From Latin accordare, to agree','communication'),
  ('understanding','understanding','/ˌʌndəˈstændɪŋ/','noun','B1','an informal agreement or shared view','["We had an understanding that the work would remain private."]','["mutual understanding","come to an understanding"]','["agreement","awareness"]','["misunderstanding"]','["understand","understood"]','["an understanding between people","understanding of something"]','["Understanding can mean knowledge as well as an informal agreement."]','neutral',94,'From Old English understandan, to comprehend','communication'),
  ('settlement','settlement','/ˈsetlmənt/','noun','B2','an agreement that ends a disagreement or legal dispute','["The parties reached a financial settlement."]','["reach a settlement","out-of-court settlement"]','["agreement","resolution"]','["dispute"]','["settle","settled"]','["a settlement between parties","settlement of a dispute"]','["Settlement ends a dispute; it does not always mean everyone agrees completely."]','formal',78,'From Old English setlan, to place or establish','society')
) as seed(slug, word, pronunciation, word_class, cefr_level, definition, examples, collocations, synonyms, antonyms, word_family, grammar_patterns, common_mistakes, register, frequency_score, origin, topic_slug)
join public.wordverse_topics topic on topic.slug = seed.topic_slug
on conflict (slug) do update set
  word = excluded.word,
  pronunciation = excluded.pronunciation,
  word_class = excluded.word_class,
  cefr_level = excluded.cefr_level,
  definition = excluded.definition,
  examples = excluded.examples,
  collocations = excluded.collocations,
  synonyms = excluded.synonyms,
  antonyms = excluded.antonyms,
  word_family = excluded.word_family,
  grammar_patterns = excluded.grammar_patterns,
  common_mistakes = excluded.common_mistakes,
  register = excluded.register,
  frequency_score = excluded.frequency_score,
  origin = excluded.origin,
  topic_id = excluded.topic_id,
  updated_at = now();

insert into public.wordverse_relationships (source_word_id, target_word_id, relationship_type, strength)
select source.id, target.id, seed.relationship_type, seed.strength
from (values
  ('price','cost','RELATED',94), ('price','value','RELATED',88), ('price','rate','RELATED',82), ('price','fee','RELATED',78), ('price','charge','RELATED',80), ('price','expense','RELATED',76), ('price','worth','RELATED',86),
  ('deal','agreement','SYNONYM',92), ('deal','contract','RELATED',84), ('deal','bargain','SYNONYM',82), ('deal','offer','RELATED',80), ('deal','arrangement','RELATED',74), ('deal','negotiation','RELATED',78), ('deal','transaction','RELATED',72),
  ('contract','agreement','RELATED',92), ('contract','deal','RELATED',84), ('contract','terms','COLLOCATION',92), ('contract','clause','RELATED',88), ('contract','obligation','RELATED',84), ('contract','signature','RELATED',78), ('contract','renewal','RELATED',72),
  ('terms','contract','COLLOCATION',92), ('terms','conditions','SYNONYM',86), ('terms','clause','RELATED',82), ('terms','provision','RELATED',78), ('terms','agreement','RELATED',80), ('terms','negotiation','RELATED',72), ('terms','stipulation','SYNONYM',70),
  ('bargain','deal','SYNONYM',88), ('bargain','discount','RELATED',86), ('bargain','offer','RELATED',82), ('bargain','price','RELATED',80), ('bargain','steal','SYNONYM',72), ('bargain','trade','RELATED',64), ('bargain','negotiate','RELATED',78),
  ('discount','price','RELATED',90), ('discount','bargain','RELATED',86), ('discount','reduction','SYNONYM',92), ('discount','rebate','RELATED',80), ('discount','markdown','RELATED',84), ('discount','sale','RELATED',82), ('discount','saving','RELATED',76),
  ('agreement','deal','SYNONYM',92), ('agreement','contract','RELATED',90), ('agreement','terms','RELATED',84), ('agreement','consensus','RELATED',82), ('agreement','accord','SYNONYM',88), ('agreement','understanding','RELATED',80), ('agreement','settlement','RELATED',76)
) as seed(source_slug, target_slug, relationship_type, strength)
join public.wordverse_words source on source.slug = seed.source_slug
join public.wordverse_words target on target.slug = seed.target_slug
on conflict (source_word_id, target_word_id, relationship_type)
do update set strength = excluded.strength;
