-- First-party, privacy-conscious Journal analytics.
-- Visitor keys are one-way daily hashes generated by the application; raw IP addresses are never stored.

create table if not exists public.blog_post_view_events (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.blog_posts(id) on delete cascade,
  visitor_key text not null,
  user_id uuid references public.profiles(id) on delete set null,
  viewed_on date not null default current_date,
  created_at timestamptz not null default now(),
  unique (post_id, visitor_key, viewed_on)
);

create table if not exists public.blog_post_daily_metrics (
  post_id uuid not null references public.blog_posts(id) on delete cascade,
  metric_date date not null,
  views integer not null default 0 check (views >= 0),
  unique_visitors integer not null default 0 check (unique_visitors >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (post_id, metric_date)
);

create index if not exists blog_post_view_events_post_date_idx on public.blog_post_view_events(post_id, viewed_on desc);
create index if not exists blog_post_daily_metrics_date_idx on public.blog_post_daily_metrics(metric_date desc);

create or replace function public.blog_metrics_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists blog_post_daily_metrics_updated_at on public.blog_post_daily_metrics;
create trigger blog_post_daily_metrics_updated_at
before update on public.blog_post_daily_metrics
for each row execute function public.blog_metrics_updated_at();

create or replace function public.record_blog_post_view(
  input_post_id uuid,
  input_visitor_key text,
  input_user_id uuid default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_event_id uuid;
begin
  if not exists (
    select 1
    from public.blog_posts
    where id = input_post_id
      and status = 'PUBLISHED'
      and visibility in ('PUBLIC', 'UNLISTED')
      and deleted_at is null
  ) then
    return false;
  end if;

  insert into public.blog_post_view_events (post_id, visitor_key, user_id)
  values (input_post_id, input_visitor_key, input_user_id)
  on conflict (post_id, visitor_key, viewed_on) do nothing
  returning id into inserted_event_id;

  if inserted_event_id is null then
    return false;
  end if;

  insert into public.blog_post_daily_metrics (post_id, metric_date, views, unique_visitors)
  values (input_post_id, current_date, 1, 1)
  on conflict (post_id, metric_date) do update
  set views = public.blog_post_daily_metrics.views + 1,
      unique_visitors = public.blog_post_daily_metrics.unique_visitors + 1,
      updated_at = now();

  return true;
end;
$$;

alter table public.blog_post_view_events enable row level security;
alter table public.blog_post_daily_metrics enable row level security;

drop policy if exists "Platform admins read blog view events" on public.blog_post_view_events;
create policy "Platform admins read blog view events" on public.blog_post_view_events
for select using (public.is_admin());
drop policy if exists "Platform admins read blog metrics" on public.blog_post_daily_metrics;
create policy "Platform admins read blog metrics" on public.blog_post_daily_metrics
for select using (public.is_admin());

revoke all on public.blog_post_view_events, public.blog_post_daily_metrics from anon, authenticated;
grant execute on function public.record_blog_post_view(uuid, text, uuid) to service_role;
